### ISSUE TITLE
MiBi-Portal does not allow 2 validations at the same time

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#105]
Open two browser tabs. Upload the attached file in one tab and directly afterwards in the other tab. There may be two results:
1: Data in the first tab is already validated and validation immediately starts in the second tab.
2: Data in the first tab is still being validated. Sometimes it takes more than one minute. If so, data in the second tab does not start to be validated until the first tab is complete. It does not matter whether both tabs are in the same browser or one is in Firefox and the other in Chrome. Both was tested from the same computer.
The question is: Can several labs validate their Probeneinsendebogen at the same time or will there be a 'traffic jam'?

[Erreger-Alternativnamen_Testdatei.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2348161/Erreger-Alternativnamen_Testdatei.xlsx)

See comment below!
No longer applicable - caching works for validation button and upload

**Comment by draaw** [comment]
I can see a third result: works as desired
maybe a proxy issue?

**Comment by dptolle** [comment]
Needs further testing

**Comment by draaw** [comment]
The performance issue is solely related to the fuzzy search. As long as there is no other solution, the suggestion is to create a cache with most common search items. The cache can be created at start time of the system.
Additionally: at the moment there is already a cache system implemented. For an unknown reason the cache does not work for the first click on "Validieren"
