### ISSUE TITLE
Display date of last code commit (to client or server)

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#106]
As a mibi-user I would like to see the date of the last code commit (client or server) displayed on the frontend.

**Comment by draaw** [comment]
The version number should better consist only of the date of the last modification of the Server/Client.
Concrete: I suggest to put in the bottom left corner: "Letztes Update: 12.09.2018"

**Comment by afalenski** [comment]
Two possibilities, please choose either 2a or 2b.
![mpc106_DisplayVersionNumber.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/c76f818b-60fb-4414-a2ad-889b5748115d)

**Comment by draaw** [comment]
I like 2a

**Comment by dptolle** [comment]
Was genau bedeutet das Datum 'Letztes Update'?

**Comment by draaw** [comment]
means: neweset deployment date - client or server related - no matter

**Comment by draaw** [comment]
Looks great!
But: actually, it shows "Letzte Änderung: heute um 02:00 Uhr". Can this be correct? I mean: 02:00 Uhr?
