### ISSUE TITLE
Add Data Protection Regulation to site

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#107]
As a portal user I would like to know about the Data Protection rules of the portal.

Therefore, two links are needed:
1. in the registration page https://epilab02.bfr.berlin/users/register called "Datenschutzhinweise". Content follows
2. in the general footer called "Datenschutzerklärung" having the same content as https://www.bfr.bund.de/de/datenschutzerklaerung-107546.html

**Comment by dptolle** [comment]
Might need to fix the styling a bit.

**Comment by draaw** [comment]
Please change "Datenschutz Hinweise" -> "Datenschutzhinweise"

**Comment by draaw** [comment]
Please replace "Datenschutzhinweise" by "Bitte beachten Sie unsere Datenschutzhinweise (LINK) für dRegistrierung sowie unsere allgemeine Datenschutzerklärung (other (footer) LINK)."

Additionally:
please delete 3.2, 3.3, 3.4, 3.5, 3.6 in the (footer) data protection page
and add (new)
"
3.2 Welche personenbezogenen Daten werden im Rahmen der Registrierung verarbeitet?
siehe hierzu unsere Datenschutzhinweise für das MiBi-Portal (LINK)
"
