### ISSUE TITLE
Display original (uploaded) values in data grid

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#109]
As a mibi-user I would like to see the values from the originally uploaded Excel sheet as a tooltip on the data-grid.

color: ?

**Comment by draaw** [comment]
Looks great!
Two suggestions:
- Rename "Ursprüngliche Daten:" to "Ursprünglich:"
- if "Original" was (trimmed) empty, say "Ursprünglich: <leer>"

**Comment by afalenski** [comment]
The original text is now shown twice: In the blue speech bubble in a sentence and in the grey speech bubble as a keyword. Do we really want this? If the grey speech bubble is going to be kept the text in the blue speech bubble should be shortened:
Old: "Erreger erkannt. Ursprünglicher Text [User's text] wurde durch den Text aus ADV-Katalog Nr. 16 ersetzt."
New: "Erreger erkannt. Ursprünglicher Text wurde durch den Text aus ADV-Katalog Nr. 16 ersetzt."

**Comment by afalenski** [comment]
One more thing: Please add in the grey speech bubble a space character between "Ursprünglich:" and the original text.

**Comment by draaw** [comment]
Sorry, for the comment above something was missing, I meant:
- if "Original" was (trimmed) empty, say "Ursprünglich: <leer>"

Ansonsten: great!

**Comment by dptolle** [comment]
@afalenski : Soll der Text 'ADV-16-Code ${original} wurde erkannt & durch den entsprechenden ADV-Text ${corrected} ersetzt.' auch angepasst werden?  Sowas wie: 'ADV-16-Code wurde erkannt & durch den entsprechenden ADV-Text ${correctedEntry.corrected} ersetzt.'?

**Comment by afalenski** [comment]
@draaw : Please comment your view on my first remark from Sep 26th.
@dptolle : This is what I wrote, but aaw's view on this is needed.

**Comment by draaw** [comment]
Its a good suggestion, I agree.

**Comment by afalenski** [comment]
Very nice, thanks.
