### ISSUE TITLE
Hourglass missing after uploading Einsendebogen

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#110]
As a portal user I would like to see the hourglass when I upload an Einsendebogen, the server is validating and I need to wait for the answer

**Comment by dptolle** [comment]
@draaw I can't reproduce the bug with the test dataset I am using.  Could you please attach the Einsendebogen you used when observing it.

**Comment by draaw** [comment]
try e.g. https://github.com/SiLeBAT/mibi-portal-client/files/2348161/Erreger-Alternativnamen_Testdatei.xlsx
