### ISSUE TITLE
Show NRL in MiBi-Portal

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#111]
As a MiBi-Portal user I would like to see directly to which NRL my samples will be sent. If I upload a dataset with a pathogen that no NRL would get (e.g. "Enterobacteriaceae") I would like to see this as an error.
From now on, we will ignore the lab chosen in the Probeneinsendebogen.

Create a new read-only column "NRL" with light grey background which should become the new column 1. Errors are to be marked in red and should appear in the first pathogen column.
Error message:
code: 96
level: 2 (= Error)
message: 'Dieser Erreger wird von keinem BfR-Labor untersucht.'

Edit messages: 
- Old error: "Erreger nicht erkannt. Der verwendete Text/Code kodiert keinen Erreger, der am BfR untersucht wird." -> new: "Erreger nicht erkannt."
- Old warning: "Ausgewähltes NRL passt nicht zu dem gewählten Erreger." -> New: No message

Note: The user's table should look like in Excel and thus the NRL should NOT appear somewhere in the middle of the table next to the pathogen.

Valid NRLs/KLs/Labs:
- KL-Leptospira
- KL-Yersinia
- NRL-AR
- NRL-Campy
- NRL-Listeria
- NRL-Salm
- NRL-Staph
- NRL-Trichinella
- NRL-Vibrio
- NRL-Virus
- NRL-VTEC
- L-Bacillus
- L-Clostridium
[https://app.zenhub.com/files/103999212/9d67b70b-adc7-4387-b64f-6675757427b6/download](https://app.zenhub.com/files/103999212/9d67b70b-adc7-4387-b64f-6675757427b6/download)
[https://app.zenhub.com/files/103999212/16dc4f43-18d7-44f4-9168-d636f37affc0/download](https://app.zenhub.com/files/103999212/16dc4f43-18d7-44f4-9168-d636f37affc0/download)

Comment: "Enterobacteriaceae" is a valid ADV16 text.

**Comment by dptolle** [comment]
@afalenski Should there be a warning if the computed NRL does not match the NRL given in the Einsendebogen header?
Please Provide error text as well as warning text

**Comment by afalenski** [comment]
For now, we have such a warning. However, we will 'publish' the NRL column only when we can split data into several Probeneinsendebogen. Then we will ignore the chosen lab and we will not need a warning anymore.

Error message:
code: 96
level: 2 (= Error)
message: 'Dieser Erreger wird von keinem BfR-Labor untersucht.'
property: [new internal name for column 'NRL']

**Comment by afalenski** [comment]
Good results, but not perfect. Please have a look at the first of the two uploaded Excel sheets, the one with the pathogen filter (see above). Then upload the test sheet in this comment and compare rows 7, 15, 16, 26, 31, 32, 33, 52 in the QA portal with the pathogen filter.
[https://app.zenhub.com/files/103999212/bf4e9668-ccff-47f4-9b8b-92b727b7e013/download](https://app.zenhub.com/files/103999212/bf4e9668-ccff-47f4-9b8b-92b727b7e013/download)

**Comment by afalenski** [comment]
Good job! Done.
