### ISSUE TITLE
Intensify saturation of yellow cell background

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#116]
As a MiBi-Portal user I would like to see a warning as a yellow coloured cell. Currently, the yellow background colour is barely different from white on some monitors.

**Comment by afalenski** [comment]
Please change the colour to rgba (255, 240, 97, 0.5)

**Comment by GerberI** [comment]
please verify color

**Comment by GerberI** [comment]
All error colors are darkened now

**Comment by afalenski** [comment]
Yellow is much easier to differ from white on screens with a general yellowish hue. All colours are fine. Done.
