### ISSUE TITLE
Add icons to menu buttons

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#141]

**Comment by afalenski** [comment]
Please enlarge space between white icon and white font to 6 pixels
Enlarge distance between "Probendaten" and "Anmelden" to 67 pixels, like in the productive MiBi-Portal (67px between 'n' and 'A').

**Comment by afalenski** [comment]
The second part is done.
About the 6 pixel distance: The distance between icon and font varies:
- [ ] Validieren: 1 px, please change to 3 px (the icon looks - admittedly - too far away with 6 px; but too near with 1px)
- [ ] Exportieren: 5 px, please change to 6 px
- [x] Schließen: 6 px
- [x] Hochladen: 6 px
- [ ] Excel-Vorlage: 5 px, please change to 6 px

And yes, you can see this without counting pixels.

**Comment by dptolle** [comment]
@draaw Seriously? Individual pixel spaces for each icon?
