### ISSUE TITLE
Scrollbar visible when waiting for validation

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#152]
Since fixing bug https://github.com/SiLeBAT/mibi-portal-client/issues/146 a small scrollbar is visible on the right when you upload a test sheet and wait for the validation. Please hide scrollbar when no data is displayed.

**Comment by GerberI** [comment]
Fixed by #171

**Comment by afalenski** [comment]
I ain't seein' no scrollbar. The li'l thin' musta disappeared. Both in Firefox and in Chrome. Done.
