### ISSUE TITLE
ADV8 abbreviations with x: Allow more abbreviations

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#154]
As a MiBi-Portal user I would like to be able to fully abbreviate the ADV8 code (Betriebsart). Currently, it is possible to write 6xxxxxx, 600xxxx and 6000xxx and the "x" is replaced by '0'. Please add replacements for 60xxxxx, 60000xx and 600000x.
[MiBi-TEST_ADV8.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2694496/MiBi-TEST_ADV8.xlsx)

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #86](https://github.com/SiLeBAT/mibi-portal-server/issues/86) via [**ZenHub**](https://www.zenhub.com/)
