### ISSUE TITLE
Improve autotext suggestions for E. coli

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#155]
If "E.coli, kommensal" is given in column "Erreger (Text aus ADV-Kat-Nr.16)", "Escherichia coli" should be shown in dropdown suggestions.
[mps53_autocorrection.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2694518/mps53_autocorrection.xlsx)

DevNote: use alias, remove ',' and ' ' and do a lowercase beforehand

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #88](https://github.com/SiLeBAT/mibi-portal-server/issues/88) via [**ZenHub**](https://www.zenhub.com/)
