### ISSUE TITLE
Date misinterpretation

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#156]
The date 30.09.1902 in the Probeneinsendebogen is transformed to 30.09.2002 by the MiBi-Portal.
[mpc156_Dates.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2695069/mpc156_Dates.xlsx)

**Comment by GerberI** [comment]
For closing this ticket a deeper discussion is neccessary. Hence turned back to backlog.

Short: import formatted strings or values from excel file <-> all validation by sever or prevalidation of spelling errors by client

Problem description:
There are two possible ways to import an excel table into the portal: the real values behind the cells can be used or the values can be formatted by the cells format codes and converted to strings. The second method is the actual one. The date values are converted to formatted date strings and so the first to digits of the year get lost. To close the ticket the real values must be imported.
This leads to a different conception of reading tables and validating the values.

Actual conception:
The imported and preformatted strings from the excel table are directly sent for validation to the server.

New conception:
The imported cell values are checked and typed and then converted to strings for sending to the server. By checking it is possible to detect simple errors and handle them before sending. So there could be a prevalidation step after uploading an excel file. After the user handles the first spelling errors the corrected data will be sent to the server and validated again for logical errors.

**Comment by draaw** [comment]
An excellent suggestion, which I understand as follows: potential gaps between what is visible in Excel and what might be meant is going to be part of the validation procedure and shown to the user as potential error that he/she needs to approve

**Comment by GerberI** [comment]
Replaced this with refactoring tickets mps147 and mpc293
