### ISSUE TITLE
Remove Browser auto-complete dropdown for Institute selection

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#158]

**Comment by birgitlewicki** [comment]
Fix needs to be tested on a system where the bug occured as I cannot reproduce it.

**Comment by afalenski** [comment]
When I click into the institue field and type "bay" I get three suggestions for the "Bayerisches Landesamt" which I find quite helpful. I see no difference between the productive MiBi-Portal and epilab02. A more detailed bug description would help.
