### ISSUE TITLE
Avoid multiple sending of same data

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#162]
As a portal user i would like to be warned if I am going to re-send the same dataset within the same session in order to not annoy the NRLs

As a NRL user i would like to see in the mail that the user has already sent the Einsendebogen in the same session: "Die Datei "[Dateiname]" wurde in derselben Browser-Session bereits gesendet."

Dev Note: Create new Dialog Box, "Sie haben diesen Einsendebogen bereits gesendet. Wollen Sie die Daten wirklich nochmal senden?"

**Comment by GerberI** [comment]
Der Kommentar in der Mail lautet nun wie folgt:
Warnung vom MiBi-Portal: Der Einsendebogen wurde vom Benutzer in der selben Browser-Session bereits gesendet.
ORIGINAL BENUTZER KOMMENTAR

**Comment by afalenski** [comment]
Very good! Done.
