### ISSUE TITLE
Warn the user if the given NRL is not one of the accepted options.

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#167]

**Comment by draaw** [comment]
Message: "Das ausgewählte Labor im Kopf Ihres Probeneinsendebogens entspricht keiner der möglichen Vorauswahlen. Bitte wählen Sie ein Labor aus der vorhandenen Liste."

Please allow exceptionally also "NRL Verotoxinbildende Escherichia coli" as a surrogate for "NRL Escherichia coli einschließlich verotoxinbildende E. coli"
