### ISSUE TITLE
Commenting before sending

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#173]
As a portal user I would like to add a comment to my data, that should be part of the mail that goes to the NRLs.

**Comment by dptolle** [comment]
Requires new Server Major version.

**Comment by afalenski** [comment]
@draaw : What is your opinion on the ideas stated in mps#91?
https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/silebat/mibi-portal-server/91
