### ISSUE TITLE
Missing alternative names for images/icons

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#184]
As a user i would like to see descriptive alternative names for images and icons when i've disabled images in my browser for some reason.
As a user having uploaded a data sheet and waiting for validation results I see the text "...alt" which makes me think I am using an old version of the MiBi-Portal.

![mibi.PNG](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/ef35a977-713a-4276-be5d-5e1bc69fc692)

Solution: Make the fonts from external systems available on web app host.

Steps to do:

- identify required fonts
- download fonts and add them to assets folder
- add google-fonts.css
- remove font links to external sources 

for fonts download see: [Web-Font-Helper](https://google-webfonts-helper.herokuapp.com/fonts)

**Comment by afalenski** [comment]
Before:
![image.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/9adb61e8-8648-4877-85fd-d361a4a28803)

Now:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/6b16ae5a-1c4a-49a2-9954-fbd13e25cc30)

**Comment by afalenski** [comment]
Reviewed by Dev.
Done.
