### ISSUE TITLE
Add empty space in error message

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#186]
As a MiBi-Portal user I would like to read error messages with correct punctuation. Please add an empty space after the fist full stop in the following error messages:

- [ ] Falscher Code.ADV9 - Codes sind maximal 8 Ziffern lang. (Error 74)
- [ ] Falscher Code.ADV2 - Codes bestehen aus 2 Ziffern. (Error 76)
- [ ] Falscher Code.ADV2 - Codes bestehen ausschliesslich aus Ziffern. (Error 77)
- [ ] Falscher Code.ADV3 - Codes bestehen aus 6 Ziffern. (Error 78)
- [ ] Falscher Code.ADV3 - Codes bestehen ausschliesslich aus Ziffern. (Error 79)
- [ ] Falscher Code.ADV12 - Codes bestehen aus 3 Ziffern. (Error 80)
- [ ] Falscher Code.ADV12 - Codes bestehen ausschliesslich aus Ziffern. (Error 81)
- [ ] Falscher Code.ADV4 - Codes bestehen aus 2 Ziffern. (Error 82)
- [ ] Falscher Code.ADV4 - Codes bestehen ausschliesslich aus Ziffern. (Error 83)
- [ ] Falscher Code.ADV8 - Codes bestehen aus 7 Ziffern. (Error 84)
- [ ] Falscher Code.ADV8 - Codes bestehen ausschliesslich aus Ziffern. (Error 85)

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #98](https://github.com/SiLeBAT/mibi-portal-server/issues/98) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #99](https://github.com/SiLeBAT/mibi-portal-server/issues/99) via [**ZenHub**](https://www.zenhub.com/)

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #100](https://github.com/SiLeBAT/mibi-portal-server/issues/100) via [**ZenHub**](https://www.zenhub.com/)
