### ISSUE TITLE
New warning: Data says it is a ZoMo sample

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#191]
As an analyst I would like all ZoMo samples to be defined as ADV4-code = 81 ("Zoonosen-Monitoring - Planprobe"). If a MiBi-Portal user uploads data which comply with the ZoMo sample rules but gives as reason ADV4-code = 10 ("Planprobe") both ADV4 cells should be coloured in yellow and show the warning "Ihre Daten passen zum Zoonosen-Stichprobenplan. Bitte prüfen Sie noch einmal, ob Sie nicht als Grund Code 81 bzw. Text "Zoonosen-Monitoring - Planprobe" angeben sollten."

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #157](https://github.com/SiLeBAT/mibi-portal-server/issues/157) via [**ZenHub**](https://www.zenhub.com/)
