### ISSUE TITLE
User should be logged out after 24h of inactivity

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#192]
As a portal user I want to "really" automatically be logged out after 24 hours. 

DevNote: Check Token on boot & remove user from local storage & store if invalid

Note: Do answer the question why the token is still vaild on the server side - even after two daysnot logging out the mails are sendable. So, not only the removal of the token on the client side can not be the solution

**Comment by afalenski** [comment]
This test did not work:
Browser = *Firefox* 60.5.2esr
- Login, close tab (not Browser), directly open new Epilab02-MiBi-Portal -> I was logged out and had to login anew

These tests worked: 
Browser = *Chrome* Version 67.0.3396.62
- [x] Login, close tab (not Browser), directly open new Epilab02-MiBi-Portal
- [x] Login, close Browser, open Chrome anew and go to Epilab02-MiBi-Portal (max 20 sec later)

To be tested:
- [ ] Login, close Browser, open Chrome anew and go to Epilab02-MiBi-Portal (1 hour later)
- [ ] Login, close Browser, open Chrome anew and go to Epilab02-MiBi-Portal (2 hours later)
- [ ] Login, close Browser, open Chrome anew and go to Epilab02-MiBi-Portal (25 hours later)

**Comment by dptolle** [comment]
@draaw @afalenski Could you please re-test this with a non-bfr Computer/firefox.  I get the same errors with my bfr Desktop, but it seems to be working fine with my Mac.  I suspect that the error is caused by bfr-firefox configuration, which appears to not persist local storage (the place where we store User information).

**Comment by afalenski** [comment]
Yes, with Firefox Portable 66.0.1 (64-bit) you can close the browser, directly open the MiBi-Portal again and you are still logged in (at BfR computer).

**Comment by afalenski** [comment]
All tests with Firefox Portable 66.0.1 and Chrome Version 67.0.3396.62 worked. The strange behaviour of the BfR-Firefox (Firefox 60.5.2esr) remains. Ticket done.
