### ISSUE TITLE
ComboBox overhaul

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#193]
The combobox for the agents behaves sometimes in a strange way. Examples:
- hard to click on it
- the combobox opens in the field above or below
- the combobox has the same height as the row, which may be to low to see more than one option to choose from

**Comment by dptolle** [comment]
@draaw : Should we talk about replacing Handson table?

**Comment by draaw** [comment]
@dptolle : sure, always welcome. But: do we have an alternative?

**Comment by afalenski** [comment]
Obsolete. Now we have replaced Handson table.
