### ISSUE TITLE
ZoMo Warning appears although combination is valid

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#195]
As a MiBi-Portal user I would like to receive a warning for ZoMo samples (error code 49) only if the combination of year, ADV2+3+8 is really not valid.

Dev-Note: Check file "ZSP2019_20180118.xlsx" sent via email on 06.03.2019@16:35

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #109](https://github.com/SiLeBAT/mibi-portal-server/issues/109) via [**ZenHub**](https://www.zenhub.com/)
