### ISSUE TITLE
Scrolling down with mouse wheel in Firefox is limited

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#196]
As a portal user who has uploaded more data than one screen can show I would like to scroll down with the mouse wheel. Currently, in epilab02 using Firefox it is only possible to scroll when the mouse hovers over the scrollbar. It is not possible in the rest of the browser window.

- in Chrome scrolling is normal in epilab02
- in the productive MiBi-Portal scrolling is normal

Test using e.g. this file:
[MiBi-TEST_ADV16-Codes.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/2967510/MiBi-TEST_ADV16-Codes.xlsx)

**Comment by GerberI** [comment]
Solved by ticket #171

**Comment by afalenski** [comment]
Works fine. Done.
