### ISSUE TITLE
Download data as XLSX

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#20]
The Mibi-Portal user wants to save the corrected data to local machine as Probeneinsendebogen (xlsx).

AC:
- Whole input Excel file should be cloned and the relevant entries should be altered.
- Save to desktop should be initiated through a button on the Online edit screen

**Comment by birgitlewicki** [comment]
Needs further discussion about the style of the created excel file.

Implemented and deployed

**Comment by dptolle** [comment]
See follow up ticket: #59
