### ISSUE TITLE
Resizing a big table is very sluggy

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#206]
As a user i would like to have a smooth window resizing behaviour.

Dev note:
Capture the resizing of the window and disallow the table to resize while window resizing is done. Perhaps show the user a greyed out table or a loading spinner while resizing.

**Comment by GerberI** [comment]
@afalenski 
This is also true for the new data-grid but not such a mess like with the handson-table. If you think it is ok, you can close this ticket.

**Comment by afalenski** [comment]
Done.
