### ISSUE TITLE
ZSP Warning does not highlight dates

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#211]
Upload the following testsheet:
[ZSP2019-Tests.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/3079120/ZSP2019-Tests.xlsx)
The warning says that the combination of ADV2, 3, 8 and year does not match the ZoMo plan. However, the two date columns are not highlighted in yellow. Please fix.

**Comment by GerberI** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #118](https://github.com/SiLeBAT/mibi-portal-server/issues/118) via [**ZenHub**](https://www.zenhub.com/)
