### ISSUE TITLE
Limit text length in email comment

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#212]
When sending data to BfR via the MiBi-Portal it is possible to post a comment with seemingly unlimited number of characters (50000 are possible). For security reasons please limit the number of possible characters to 500 (or 75 words). Please add a counter so that the user knows how many characters are left.

Dev-note:
mat form field has already hint labels with max chars on board

**Comment by draaw** [comment]
Which security reasons do you think about?

**Comment by afalenski** [comment]
Crashing our system by posting a comment with millions of words.

**Comment by draaw** [comment]
Ok, but there is a tiny difference between 500 chars and millions of words. Maybe another reasonable limit makes sense that does not hinder for sufficient commenting.

**Comment by afalenski** [comment]
Agreed on 2000 characters.

**Comment by afalenski** [comment]
The portal truncates the text at 2000 characters. It is not possible to put more into the message field by copy&paste. Done.
