### ISSUE TITLE
If you close the browser or the browser tab you are logged out

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#216]
It was implemented that the user should be logged out after 24h of inactivity (see https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/silebat/mibi-portal-client/192). 
In the current release candidate the user is logged out immediately when the browser or browser tab is closed. This bug was found in
- [x] Chrome Portable, Version 73.0.3683.86 (Offizieller Build) (32-Bit) (*Close browser*)
- [ ] Firefox 60.5.2esr (32-Bit) BfR (*Close browser*)
- [ ] Firefox 60.5.2esr (32-Bit) BfR (*Close browser tab*)
Please fix so that the user is only logged out after 24 hours.

This bug did not appear using
- Chrome Portable, Version 73.0.3683.86 (Offizieller Build) (32-Bit) (*Close browser tab*)
- Firefox Quantum 66.0.2 (64-bit) (Portable App) (*Close browser*)
- Firefox Quantum 66.0.2 (64-bit) (Portable App) (*Close browser tab*)

**Comment by dptolle** [comment]
@afalenski We already know that this feature does not work with FF60.x.x - this is a problem with Firefox.  We also already decided that trying to find a work-around would not be worth the investment.
I can not reproduce this bug with Chrome Portable v67.0.3396.62 - please check your Chrome security settings and test again.
