### ISSUE TITLE
Before sending data inform the user that there are still warnings in uploaded data

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#220]
As a ZoMo data analyst I want the data to be as perfect as possible and this is why I want the users to be informed about existing warnings in their uploaded data before sending. 

- [x] In the wizard, show the warning "Ihre Daten enthalten noch **Warnungen**. Möchten Sie zurück zu den Daten und sie korrigieren?". The word "Warnungen" in bold face. The background should be yellow and the warning should look just like the warning when trying to send the same file twice (see screenshot below). It should appear when clicking on "Senden" in the menu bar and only if there are warnings in the data and no errors (autocorrections do not matter).
Example from the portal (duplicate sending):
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/d2d30c08-8c85-49ee-975e-2748b754d633)
- [x] When clicking "ZURÜCK ZU DEN DATEN" the wizard should disappear (as it is currently the case). When clicking "SENDEN" the E-Mails-Box should appear and show the same warning (see example from duplicate sending below).
![image.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/729a3f33-fac8-415e-be1d-eec55adab956)

**Comment by GerberI** [comment]
@afalenski 
Should the new warning also be added to the mails, like the already sent warning?

**Comment by afalenski** [comment]
No, this warning text should not be in the email.

**Comment by GerberI** [comment]
As with most of the other messages, i think this one is also a bit to long and over explaining. Consider using a message like: "Achtung, Ihre Daten enthalten noch Warnungen." It is obvious that there are no errors and the back to the data button is also very present and self-explanatory.
In general, the longer a messages becomes the more unlikely it is the user reads it. In contrast if a message is very short the user does not need to read it but just gets the information at glancing at it.

**Comment by afalenski** [comment]
Thanks for this. I shortened the sentence. I kept "möchten Sie zurück zu den Daten" because then the user knows that she/he needs to click the button "Zurück zu den Daten".
