### ISSUE TITLE
Tooltips showing the title of the page

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#237]
When a user points with the mouse over an item like a button a tooltip is shown with the title of the page. As a user i would like to see the title or information regarding the concrete item. 

Steps to reproduce the behavior (e.g. on the login page):
1. Go to 'Login'
2. Hover over 'Passwort vergessen?'
3. A tooltip appears with the text 'login'

I would expect a text like 'Gehe zu Passwort vergessen Seite' or 'Passwort vergessen'.

There are to solutions:
- Disable the tooltips
- Add a meaningful text to the child items of the page

![grafik.png](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/1ed7e2b7-3aac-4981-bc21-b22a363d9e44)

Dev-Note:
The problem is the title property of a mat-card. By setting it, hovering over the card displays a tooltip with that title.
This is a default behaviour of the html standard and browsers. A set title of an html element is passed down to the children and is shown as a tooltip.

To disable tooltips don't use the title attribute.

**Comment by afalenski** [comment]
There are not tooltips anymore - neither on the registration page, nor on the login page, nor on the password reset page. Done.
