### ISSUE TITLE
Update to angular 8

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#243]
Update connected libraries

**Comment by GerberI** [comment]
@afalenski Due to angular update the rows of the handsontable are not resizable or grabable anymore (i had to remove the header column and change it to a normal non-editable column to fix layout issues). The auto-sizing behaviour of headers is also slightly different now (perhaps better then before).

**Comment by afalenski** [comment]
In the header row there is a lot of empty space below the headlines. Could you please set the maximum height of the header row to the maximum space which is used by the headline texts?
Empty space: See Screenshot
![mpc243_Header-row-height-is-too-big.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/e18159f8-f6b1-47d3-a7aa-613e45e618c5)

**Comment by GerberI** [comment]
The empty space is there because i had to fix the header height to a constant value to overcome other layout issues with
handson table v7.
In the old version (see production system) the height was partially dynamically adjusted to the content. If you reduced
window width the height gets adjusted, then if you increased window width again you get the same effect as in the
screenshot.
Because of always fixed header height in the new version, if you reduce window width, the minimum width of the table
gets also fixed at some point (because there is no space anymore for the header text). So i choosed the value for the
fixed height to get also a reasonable experience for users using a non-wide-screen monitor.

If you still like to use another height please give me a concret value in pixels.

/// Wissenschaft im Dienst des Menschen ///

>>> afalenski <notifications@github.com> 05.03.2020 17:14 >>>
In the header row there is a lot of empty space below the headlines. Could you please set the maximum height of the
header row to the maximum space which is used by the headline texts?
Empty space: See Screenshot
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
(
https://github.com/SiLeBAT/mibi-portal-client/issues/243?email_source=notifications&email_token=ALCKQSOYVWVITSWBREBUXRLRF7FVBA5CNFSM4H5ZWU5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN54CEQ#issuecomment-595312914)
, or unsubscribe

**Comment by GerberI** [comment]
Sorry for messed up format of the last comment. I replied to the comment in GroupWise and that was not a good idea...

**Comment by afalenski** [comment]
OK, then leave it as it is. We will have our own solution soon. For me it is done then. Please change the lane to 'Done' if you do not need to work on the ticket anymore.
