### ISSUE TITLE
No banner if sending samples with validation errors fails

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#246]
As a user i would like to be informed if sending samples failed because of validation errors. I would prefer to not be able to send data at all if it is invalid.

Dev-Notes:
The coreUIReducer is buggy. The main cause is that isBusy-state and banner-state are handled in the same routine.

There is also a bug in the upload routine. If i upload a file the upload component is throwing an error by dispatching a display banner action. This has something to do with the error.clear state of this component. The upload error is not visible because after auto validation the banner gets destroyed.

I recommend to rewrite/rethink the overall banner/error code.

**Comment by afalenski** [comment]
Alright, I can see a toaster message. This ticket is done, but all in all this way of informing the user is not user-friendly enough. I will create a new ticket.
