### ISSUE TITLE
Auto-generate Probeneinsendebögen

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#257]
As a MiBi-Portal admin I would like the MiBi-Portal to auto-generate Probeneinsendebögen.

Generate the first page of the Probeneinsendebogen. It should look similar (not necessarily identical) to the current Excel sheet. The first page should contain:
- [ ] "Labor" (the BfR lab for which the data should be sent)
- [ ] User-specific information (see #256)
- [ ] Information about pathogens (in the Probeneinsendebogen in section "Bitte führen Sie folgende Untersuchungen der Isolate durch" (see #259)
- [ ] In the lower right corner add text "Geprüft durch das MiBi-Portal"

**Comment by GerberI** [comment]
Discard. :(((
We have BETTER tickets now.
