### ISSUE TITLE
Rewrite content css

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#269]

**Comment by GerberI** [comment]
@Alex for review:
Faq and Datenschutzerklärung where refactored. I changed the links in these documents so that they are opened in a new tab. The faq looks slightly different but is more responsive now. I changes the list bullets in the Datenschutzerklärung to the Datenschutzhinweise style, they are lower characters now.

**Comment by afalenski** [comment]
I like it! Done.
