### ISSUE TITLE
Browser Reload while on Profile page as authenticated user faulty

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#272]
**Describe the bug**
Browser Reload while on Profile page as authenticated user results in a URL redirect to / and appearance of a white page, rather than the refreshing of the Profile page.

**To Reproduce**
1. Log into the mibi-portal
2. Go to the User Profile page 
3. Press the browser reload button
4. See error (a redirect to / and a white page)

**Expected behavior**
Expect to land back on the Profile page

**Desktop (please complete the following information):**
 - OS:MacOS
 - Browser: chrome

**Comment by afalenski** [comment]
Bug fixed. Done.
