### ISSUE TITLE
Erroneous warning in column "Probenummer nach AVVData"

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#283]
As a MiBi-Portal user I would like to get a state-specific warning when I have given a wrong sample number in column "Probenummer nach AVVData". Currently, I get a warning in the attached testsheet for data row 5 with sample number "19-1234567-127", although the system cannot know from which German state my data come because I have not logged in.
[https://app.zenhub.com/files/103999212/5b575fe4-34c1-43f1-aa2a-a8a3ee3508a8/download](https://app.zenhub.com/files/103999212/5b575fe4-34c1-43f1-aa2a-a8a3ee3508a8/download)

**Comment by dptolle** [comment]
Works as specified.
