### ISSUE TITLE
Make rejection of data more intuitive

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#286]
As a MiBi-Portal user who has errors in his/her data and pushes the "Senden" button I find it confusing that I can see the "Senden"-popup and write a message to BfR and only afterwards I get the toaster information "Es gab einen Fehler beim Versenden...". As a user I would prefer to get the toaster information BEFORE the "Senden"-popup appears.

**Comment by GerberI** [comment]
Duplicate
