### ISSUE TITLE
Check if chrome 75 layout bug is still there

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#287]
See #238
Remove workaround css code if bug ids fixed

**Comment by GerberI** [comment]
This implicitly part of testing the new data table

**Comment by GerberI** [comment]
@afalenski 
Add would be nice to know since which chrome version this bug is gone.

**Comment by afalenski** [comment]
I could not see the bug in Chrome 65 or 79 or 83 (current version), neither in the productive nor in the test MiBi-Portal. Specific versions are not distributed by Google due to security reasons.

**Comment by GerberI** [comment]
Hallo Alex,
sehr schön. Jetzt können wir den Bug immerhin auf Version >= 75 < 79 einschränken. Ob eine dieser Version noch im
Umlauf ist werden wir dann sehen, wenn sich ein User beschwert. Alternativ wollten wir ja eh mal die Log-Dateien
durchgehen und schauen ob man rausbekommt wer welche Version verwendet.
Viele Grüße,
Isaak

/// Wissenschaft im Dienst des Menschen ///

>>> afalenski <notifications@github.com> 03.06.2020 18:51 >>>
I could not see the bug in Chrome 65 or 79 or 83 (current version), neither in the productive nor in the test
MiBi-Portal. Specific versions are not distributed by Google due to security reasons.
—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
( https://github.com/SiLeBAT/mibi-portal-client/issues/287#issuecomment-638321710) , or unsubscribe
