### ISSUE TITLE
MiBi-Portal changes dates in productive version

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#292]
Upload the attached Probeneinsendebogen and compare the dates from the Excel sheet with those in the MiBi-Portal. Only dates in row 5 are correct. In the other dates the MiBi-Portal subtracts one day. This is a serious bug and is found in the productive portal, in epilab02 and in nolar. Please consider a hotfix.
[mpc292_Dates-BUG.xlsx](https://app.zenhub.com/files/103999212/13625710-4e82-46f2-85b8-a4fc13053294/download)

**Comment by GerberI** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #146](https://github.com/SiLeBAT/mibi-portal-server/issues/146) via [**ZenHub**](https://www.zenhub.com/)
