### ISSUE TITLE
Hotfix: Change ADV3 CSV file 

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#300]
The current ADV3-CSV-file does not contain all ADV3 codes. Please update the file in the productive MiBi-Portal and in the QA portal.
See slack message from 06.09.2019@15:17

**Comment by dptolle** [comment]
@afalenski : Currently deployed on QA. Please verify that the missing ADV entries are now present so we can proceed deployment to PROD.
