### ISSUE TITLE
Transfer 'Aktenzeichen des Einsenders' to validated PDF/XLSX

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#324]
As a user I would like the MiBi-Portal to transfer the 'Aktenzeichen des Einsenders' to the validated PDF and XLSX. The 'Aktenzeichen' is on the top right on the first page of the Probeneinsendebogen.

**Comment by afalenski** [comment]
If the user enters a date into the field "Aktenzeichen", the portal changes the content.
Aktenzeichen entered: 22.06.2020
Date in PDF and in XLSX from the portal: "Mon Jun 22 2020 00:00:00 GMT+0200 (Central European Summer Time)"
PDF and XLSX from the portal should show exactly the same string the user has entered. Please adjust.

**Comment by GerberI** [comment]
This is a common bug, applicable to all fields. See mibi-portal-server#210. So i moved the ticket to QA again.

**Comment by afalenski** [comment]
Great! The Aktenzeichen is in the downloaded sheet, in the XLSX and in the PDF - even if it is a date. Done.
