### ISSUE TITLE
Add "Ort, Datum" in XLSX and PDF according to the uploaded Probeneinsendebogen

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#326]
- [ ] In the PDF and the XLSX the text above "Ort, Datum" is missing.

**Comment by afalenski** [comment]
If the user only enters a date and no place, the portal changes the content.
Date entered: 22.06.2020
Date in PDF and in XLSX from the portal: "Mon Jun 22 2020 00:00:00 GMT+0200 (Central European Summer Time)"

This is hard to read and not what the user entered. PDF and XLSX from the portal should show exactly the same string the user has entered. Please adjust.

**Comment by GerberI** [comment]
This is a common bug, applicable to all fields. See mibi-portal-server#210. So i moved the ticket to QA again.

**Comment by afalenski** [comment]
Very good! False dates, date and place, date with text ("Berlin, den 03.03.2020")... all works and not date was transformed. Done.
