### ISSUE TITLE
Ask users whether they really want to logout when data have been uploaded

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#327]
As a user who has uploaded data an then clicks on 'logout' I would like to be asked whether I really want to logout. I am already asked when I click on "Schließen" or on "Hochladen". 

- [x] Box "Abmelden", "Sie haben bereits Daten hochgeladen. Wenn Sie sich abmelden, wird die Tabelle geschlossen und Ihre Änderungen gehen verloren. Wollen Sie das?" when clicking on logout and if a dataset has been uploaded in the portal.
- [x] The box should not appear when no dataset has been uploaded (e.g. when logging in and directly logging out).
- [x] The box should not appear if the user has clicked on "Schließen" so that there are no data in the portal and the user sees the "Hochladen" screen).

**Comment by GerberI** [comment]
Why i should use an incorrect message here? How about something like: "Abmelden", "Sie haben bereits Daten hochgeladen. Wenn Sie sich abmelden, wird die Tabelle geschlossen und Ihre Änderungen gehen verloren. Wollen Sie das?

**Comment by afalenski** [comment]
Thank you! I followed your recommendation and changed the ticket text.
