### ISSUE TITLE
Change "x" in "Bitte führen Sie folgende Untersuchungen der Isolate durch"

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#330]
- Standard methods should not be called "x" but "Standard"
- ~If the user exports XLSX via button "Exportieren", he/she should get the options "Normal/Eilt", "Labor" and methods which he/she originally marked with "x" in the uploaded XLSX. This should also be true for uploading data via API and exporting an XLSX.~

**Comment by GerberI** [comment]
@alafenski
I moved the second issue to a new ticket: #335

**Comment by afalenski** [comment]
- In the PDF everything is fine: Standard methods are called "Standard" and the user's choices are called "x".
- [ ] The same should be true for the XLSX so that the colleagues in the NRLs also can differ between the standard methods and the user's choice. Please change in XLSX, too.

**Comment by afalenski** [comment]
Great! PDF and XLSX are both fine. Done
