### ISSUE TITLE
Already send warning in analysis wizard has wrong text and is shown twice

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#334]
The text of the warning in the analysis wizard is the text that appears in the mail send to the BfR and not the text the user of the portal should get. See the warning in the final send dialog.

The warning appears twice.

![a.PNG](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/e0a8d588-8f7a-4c62-a590-bea4b24ce0d7)![b.PNG](https://images.zenhubusercontent.com/5c35c98c4b5806bc2b01ed72/1db29651-4ff6-4b06-a176-4a632a27c3d1)

**Comment by afalenski** [comment]
Now, the text is there only once. Done.
