### ISSUE TITLE
User interface delay of analysis wizard if large table is loaded

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#337]
If an user imports a huge sample sheet (like 50 rows) and then clicks the send button the anaylsis wizard behaves very slow. Especially typing some text.

DevNote:
Changes in the wizard are reflected directly to the redux store. So the store does something that is very slow (perhaps updating the handson table?).

**Comment by GerberI** [comment]
It seem this issue is fixed by the new data table

**Comment by afalenski** [comment]
The wizard is quite fast, now; also its animation. Done.
