### ISSUE TITLE
Create data table: Column width and word wrap

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#351]
Column width adapts to browser window width until 1100px width; for narrower browser windows a horizontal scrollbar appears. Text in columns adapts to column width (line break).

**Comment by GerberI** [comment]
@afalenski 
I think the fixed width is obsolete. The new table adapts dynamically to any browser size, depending on the actual content. If there is no reasonable way to squeeze the table anymore, a horizontal scrollbar appears.

**Comment by afalenski** [comment]
Columns width adapts to available space in narrow browser windows and a horizontal scroll bar appears. Done.
