### ISSUE TITLE
Create data table: Display error colours

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#352]
The table shows errors (if applicable) after data was uploaded or when clicking on "validieren". If there are errors in the data the browser table displays colours for errors (red), warnings (yellow) and auto-corrections (blue).

**Comment by GerberI** [comment]
@afalenski 
This ticket introduces the following bug: Empty cell is not highlighted after editing: See #202
This is because i fixed a bug in the client code that 'fixed' the server bug.

This ticket does not address the performance issues.
This ticket does not include the darkened highlight colors.

**Comment by afalenski** [comment]
The error colours are shown and are correct. They are a bit lighter in saturation than the original colours, but this will be adjusted in ticket [mpc#116](https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/silebat/mibi-portal-client/116).
As the non-highlighted empty cell after editing is a server bug, this display of error colours will be tested with ticket [mps#202](https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/silebat/mibi-portal-server/202). 
Done.
