### ISSUE TITLE
Create data table: Speech bubbles

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#353]
Errors, warnings and auto-corrections are explained in speech bubbles (text from error code table) when hovering with the mouse over a coloured cell.

**Comment by GerberI** [comment]
See also: #389

**Comment by afalenski** [comment]
Speech bubbles are visible and contain the correct text. Using a 500-row test sheet pop-up behaviour is quite fast (Firefox 68), good (Chrome 79) and okay (Firefox 60). Done.
