### ISSUE TITLE
Create data table: Edit text

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#354]
When double clicking into a cell the text can be edited (columns 3-21).

**Comment by GerberI** [comment]
@afalenski 
Single click also does the job :)

**Comment by afalenski** [comment]
Editing cells works in Chrome. In Firefox there are performance issues (see email on 17.04.2020@18:37).

**Comment by GerberI** [comment]
Additional Feature: Editing is confirmed with ENTER and cancelled with ESC

**Comment by afalenski** [comment]
No performance issues anymore. Thanks for the additional features! Done.
