### ISSUE TITLE
Create data table: Pathogen dropdown selection

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#355]
If a pathogen (column 5) is erroneous and if the text recognition finds possible alternative pathogen texts (from ADV catalog no 16 or from an additional pathogen list) the pathogen cell displays a white dropdown symbol. Clicking on this a dropdown list displays up to 20 suggestions for pathogens. The text in the cell can still be edited.
![mpc349_pathogen-correction-suggestions.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/a24bbcfb-959d-4a84-bf1d-818348f4e0e5)

**Comment by GerberI** [comment]
Additionally i've elevated the editor so that it overlaps the table headers (like with the handsontable). I thought that it is a better user experience especially with the auto correction offers list.

**Comment by afalenski** [comment]
The DropDown list is easy to read and has a nice look and feel. Just one thing which should be changed: In the productive portal it is possible to click onto the white arrow and you see directly the DropDown list. In the new version in the test portal you have to click into the cell first. Only the second click opens the DropDown list. Please adjust so that it works as in the current productive portal.

**Comment by GerberI** [comment]
I intentionally dismissed this feature. I think it is not convenient to click on that tiny Arrow to open the dropdown list. I think the user expects a cell to be selected, no matter where he clicks on the cell. As i mentioned before i think the arrow is obsolete at all. So please rethink that point. If you want the arrow to be clickable anyway, we should consider to make it more present and easier to click.

**Comment by afalenski** [comment]
I see. In this case I am happy to announce that this ticket is done.
