### ISSUE TITLE
Performance Update

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#374]
Refactoring:
The new data-grid / browser-table UI is performing slow with many rows, especially in old browsers.
Additionally loading of big sample sheets is also very slow.

Dev-Notes:
The performance update includes following sub tasks:
1 - Change behavior of the action bar in the top app bar during loading. The action bar should be displayed before a new page is loaded so that its animation can not slow down page rendering. Additionally it should not be destroyed and displayed again if action items are updated.
2 - Change busy spinner animation. The busy spinner should not destroy the page if displayed. It should only overlay the active page.
3 - Change page transition animation. Leaving a page should not be animated. It reduces the overall user experience due to stalling the rendering of the new page. It could be only useful if entering pages are loaded and rendered during that animation. That is not true for the used angular's animation framework.
4 - Use manual change detection for data-grid component. Emitting an event in a grid cell should not cause a change detection cycle for all the other cells.
5 - Use selective change detection for cells. If a cell state changes only that cell should run a change detection cycle.
6 - Move cell templates to a separate component not aware of grid's change detection. If change detection runs for the component containing the cell templates, it causes change detection for all cells to.
7 - Reduce the number of dom elements of grid cells. It is common to use not more than 1500 dom elements for a page. A huge table can have 10 of thousands of cells so every element counts. See: https://developers.google.com/web/tools/lighthouse/audits/dom-size#recommendations
9 - Change banner so it behaves like an overlay. Now it is consuming the space of the page content moving the content down if displayed. This makes displaying the banner a very costly operation especially because it is also animated.
8 - Rearrange dom of cell editor. Now the cell editor is placed inside a grid's cell. This causes the render engine to re-render the whole grid each time the editor's size is recalculated (on each key stroke or showing and hiding the editor). The editor should be placed aside the data-grid. This makes it necessary to manually update position and size of the editor.

Note:
Animations should be used to hide performance bottle necks. In our app they are the main cause for many performance problems. It should be considered to completely disable animations for the data table.

Bug:
The edge browser does not perform the page transition animations correctly. They are not canceled correctly after the animation is done, so that always two pages are active in the dom at the same time.
Solution: Animations are now disabled for edge browser.
Note: This could also be true for Safari-Browser because of strange animation behavior in the past.

**Comment by GerberI** [comment]
@afalenski 
Things to test:
1: Grid Performance (should be usable up to 500 rows, tested with newest edge, chrome and firefox)
2: Page-Transition animations from and to samples page
3: Busy-Spinner animation
4: Banner
Some bugs and minor changes: I will create separate Tickets for them.

I will take over quick tests of the whole thing with safari and the tests of the other safari tickets in the QA lane.

**Comment by afalenski** [comment]
Great performance improvements! Runs smoothly in Chrome as well as in Firefox. Concerning loading times or editing text, 500 rows are no problem anymore. Scrolling is good for 500 rows and very good for 200 rows. Done.

**Comment by afalenski** [comment]
The performance improvement is huge, indeed: Just 7 seconds for 500 rows in Firefox compared to 110 seconds before. Great! Performance in Opera is about as good as in Chrome and Firefox. In Edge, it is alright. The 500 row sheet needs 27 seconds to load and when scrolling it shows white areas where the browser still tries to render the rows. The latter is also true for 200 rows. But the improvements are sufficient. Ticket done.
