### ISSUE TITLE
Update data protection officer contact

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#376]
As product owner I would like the contact of the data protection officer to be updated on the following two MiBi-Portal webpages:
https://mibi-portal.bfr.bund.de/users/datenschutzhinweise
https://mibi-portal.bfr.bund.de/content/datenschutzerklaerung

Replace

_Christin Weigel
Bundesinstitut für Risikobewertung
Max-Dohrn-Str. 8-10
10589 Berlin
E-Mail: dsb@bfr.bund.de_

with

_Rechtsanwalt Carsten Bethke
Calandrellistr. 24
12247 Berlin
E-Mail: dsb@bfr.bund.de_

**Comment by GerberI** [comment]
Is this still true in the "Datenschutzerklärung": "Bei Fragen zur Verarbeitung Ihrer Daten und zum Datenschutz wenden Sie sich bitte an **unsere behördliche Datenschutzbeauftragte**:" ?

**Comment by afalenski** [comment]
Oh, no, thanks for mentioning! Please change to "unsere**_n_** behördlichen Datenschutzbeauftragte**_n_**" on https://mibi-portal.bfr.bund.de/content/datenschutzerklaerung.
Please also change "Unsere Datenschutzbeauftragte ist:" to "**Unser Datenschutzbeauftragter** ist:" on https://mibi-portal.bfr.bund.de/users/datenschutzhinweise. (Bold face is just to show the differences, do not type them in bold face on the webpages, please.)

**Comment by GerberI** [comment]
I already changed the gender. Question was about the "behördlich". Seems its ok, so i put the ticket again in QA

**Comment by afalenski** [comment]
Behördlich was agreed on and is correct. Done.
