### ISSUE TITLE
Hide Banner on User-Action

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#381]
As a user i would like to have the banner to disappear if i start a new user action like "Senden" or "Hochladen". This also ensures that any banners are only pointing to the last performed action.

**Comment by GerberI** [comment]
I've found this during implementing the new banner look and feel during #374 and changed it too.

**Comment by afalenski** [comment]
Now, the banner disappears immediately when the next action is started by the user. Done.
