### ISSUE TITLE
e2e tests checking for URL="Home" are always true

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#382]
Some e2e tests check if the active page is the home page by checking if the URL includes a string stored as paths.root. This string is set to "/", so the test always will be is true because a URL always contains the "http://" string.
For example the profile page is tested against use by an anonymous user which should redirect to the home page. This has never happened because of a bug (#272), but the test never failed.

**Comment by GerberI** [comment]
@afalenski 
After fixing the bug one e2e test fails because the mibi-portal has a different behavior than the test expects. So i need a suggestion if i should adapt the test to the actual behavior or change the behavior of the portal to adapt the one in the test.
User action: Navigate to '/users/profile' by the browser nav bar as an unauthenticated user.
- [ ] MiBi-Portal: The login page is shown.
- [ ] e2e Test: The Home Page should be shown.
Please select the desired behavior.

**Comment by afalenski** [comment]
How should I reproduce this? I did what is described in #272:
- log in into MiBi-Portal -> I see the profile page
- reload browser tab -> I see the profile page

When I logout and copy  '/users/profile' into the address field behind the home address of the test server, I see (after 2 seconds seeing a white browser tab) the login page. How can I **navigate** to the profile when not logged in? What is an unauthenticated user?

**Comment by GerberI** [comment]
#272 has nothing to do with it.
Your second flow is the correct one: Be logged out (=unauthenticated) and type https://epilab-dev.bfr.berlin/users/profile in the browser url input. As there is no profile here as you stated correctly, the question is should the user be redirected to the Login page or to the Home page.

**Comment by GerberI** [comment]
My opinion: As for other invalid routes, the user is redirected to the homepage, so this would be the default behavior. But if i want explicitly visit the profile page a redirect to login would also be fine. So i have no preference about the redirect, that's why i asked you :)

**Comment by afalenski** [comment]
Thanks for the explanation. If I took the effort to type in the link to the profile page I would find it comfortable to see the login page. So I voted for the first option (see above).

**Comment by GerberI** [comment]
thx, Done
