### ISSUE TITLE
Data table border widths are not as thin as intended.

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#390]
The border widths should be 1px and not 2px. This is a rendering issue. Browser rendering of 0.5px borders unprecise.

**Comment by GerberI** [comment]
Only possible solution was to define borders only for bottom/right for the grid cells. This leads to an undesired behaviour of the cursor beeing off by 1px. I think this is issue is not as bad as having 2px fat borders.

**Comment by afalenski** [comment]
Looks good; no clipping or any strange behaviour when zooming or scrolling. Done.
