### ISSUE TITLE
Update all client libraries

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#394]

**Comment by GerberI** [comment]
@alafenski
Things you could test: Upload files, Password-Strength-Meter, Login, Send Samples.
Only visible change should be the password-strength-meter looking a little bit different.

**Comment by afalenski** [comment]
1) Password strength meter is fine.
2) Sending: 
2a) Upload a correct Probeneinsendebogen and click on "Senden": The sheet is sent.
2b) Upload a Probeneinsendebogen containing errors, correct all errors but make one mistake (Date = "30.9.18"), click on "Senden": **The sheet is NOT sent.** A message appears "Es gab einen Fehler beim Versenden der Datei...". But **no error is shown** in red.
2c) Upload a Probeneinsendebogen containing errors, correct all errors but make one mistake (Date = "30.9.18"), click on "Validieren" -> date is shown in red; correct to "30.9.2018" and then click "Senden" -> email is sent.
3) Login and logout are fine.
Because the behaviour in 2b is the same in the productive portal, this is feature and does not need to be corrected here.
Done.
