### ISSUE TITLE
Add “Probenummer nach AVV-Data” to “Ihre Probenummer” if “Ihre Probenummer” ist empty

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#402]
Add “Probenummer nach AVV-Data” to “Ihre Probenummer” if “Ihre Probenummer” ist empty

- do only in data rows for NRL-AR
- do only in Excel sheet for BfR; NOT in Browser and NOT in PDF for user

**Comment by GerberI** [comment]
Was already done in mibi-portal-server#175 for all NRLs.
