### ISSUE TITLE
Add new ADV catalogs 2021

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#414]

**Comment by GerberI** [comment]
@afalenski 
As i predicted: Now some of the new ADV16 codes are duplicated because we had them already in our ADV16_bfr extension catalog. They are displayed twice in the auto correction drop down selection.
I will compare the codes and fix our bfr catalog, so that there are no duplicates anymore. Please add that to your workflow, so that we check that the next time new catalogs are released.

**Comment by GerberI** [comment]
I removed following duplicated entries from ADV16_bfr:
016######Genus Trichinella
016######Trichinella britovi
016######Trichinella nativa
016######Trichinella pseudospiralis
016######Trichinella spiralis
016######Vibrio campbellii
016######Vibrio furnissii
016######Vibrio harveyi
016######Vibrio metschnikovii

**Comment by GerberI** [comment]
Removed also:
016######AmpC-verdächtiger Escherichia coli
016######Carbapenemase-verdächtiger Escherichia coli
016######ESBL-verdächtiger Escherichia coli

**Comment by GerberI** [comment]
So, the names for the 'verdächtiger Escherichia coli' has changed the selectors for mapping the pathogens to the NRL-AR has to be fixed to. I replaced the selector:
- ^.*-verdächtiger Escherichia coli$
with the following, representing the new entries in ADV16 2021:
- ^Escherichia coli, AmpC verdächtig$
- ^Escherichia coli, Carbapenemase verdächtig$
- ^Escherichia coli, ESBL verdächtig$

**Comment by GerberI** [comment]
@afalenski 
These new additional pathogens are selected for the "L-Clostridium" by its "^.*Clostrid.*$" selector. Please verify if these are really meant to be sent to the NRL:
016#000#5520651####cpa-Gen (Clostridium perfringens)######20210101#
016#000#5520652####cpe-Gen (Clostridium perfringens)######20210101#
016#000#5520653####cpb2-Gen (Clostridium perfringens)######20210101#
016#000#5520654####cpb1-Gen (Clostridium perfringens)######20210101#
016#000#5520655####etx-Gen (Clostridium perfringens)######20210101#
016#000#5520656####iap-Gen (Clostridium perfringens)######20210101#
016#000#5520660####Sequenzen zum Nachweis von Clostridioides-difficile-Genfragmenten######20200101#

**Comment by afalenski** [comment]
Great, the new ADV catalogs are working fine on MiBi-Portal dev and production.
Thank you for all the adaptations! Done.
