### ISSUE TITLE
Update GDPR information

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#416]
As a user I would like to be able to contact the data protection officer (has changed) and to reach the GDPR webpage (link outdated).

- [x] Data protection officer: The old information needs to be replaced by the new one on these two sites:
https://mibi-portal.bfr.bund.de/content/datenschutzerklaerung
https://mibi-portal.bfr.bund.de/users/datenschutzhinweise

Old:
Rechtsanwalt Carsten Bethke
Calandrellistr. 24
12247 Berlin
E-Mail: dsb@bfr.bund.de

New:
Frau Janina Rochon
Bundesinstitut für Risikobewertung (BfR)
Postfach 12 69 42
Tel 030 18412 31002
E-Mail: dsb@bfr.bund.de

- [x] Change to DS-GVO on the page https://mibi-portal.bfr.bund.de/content/datenschutzerklaerung
On the page "Datenschutzerklärung" the link "Europäischen Datenschutz-Grundverordnung (DS-GVO)" does not work; the site seems to have moved to https://eur-lex.europa.eu/legal-content/DE/TXT/HTML/?uri=CELEX:32016R0679; please exchange the link behind the text but keep the text the same.

**Comment by GerberI** [comment]
Change to DS-GVO: Both links work, but i used the new link. (old is pdf, new is html)
