### ISSUE TITLE
Mail errors

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#419]
As a user I want to be informed if my data is not sent to BfR, e.g. because the email address has changed and the portal contains an outdated email address.

Ideas
Email error messages need a little time. Until it arrives, the user might have logged out already. 
- Send email to user which has initiated the MiBi-Portal email by uploading and sending data to a specific BfR lab.
- Send email to admin so that he/she is informed and can change the email address in the system.
- Keep user data in MiBi-Portal and resend to BfR when email has been changed.
- Set banner / toaster "Bitte auf Bestätigung der erfolgreichen Versendung warten".
- Set banner / toaster "Senden erfolgreich" or "Senden fehlgeschlagen".

**Comment by GerberI** [comment]
Duplicate
