### ISSUE TITLE
Update all Client Production Libraries (except angular)

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#425]
major: (@auth0/angular-jwt), angular-file, (ngx-moment), rxjs
minor: jquery, moment

**Comment by GerberI** [comment]
Following libraries could not be updated, they depend on angular > 8: @auth0/angular-jwt, angular-file, ngx-moment, rxjs

**Comment by GerberI** [comment]
@afalenski 
Angular 8 is not supported anymore and we should update to 9 asap.
Things to test (roughly):
tooltips, file export

**Comment by afalenski** [comment]
- Tooltips are visible, pop up rapidly and contain the correct content
- Excel file export works, autocorrections are highlighted in turquoise
Done.
______
**Tested with**
OS: Windows 10

Datasets: 
- Mibi-TEST_Erreger.xlsx

Browsers:
- Google Chrome Version 91.0.4472.164 (Offizieller Build) (64-Bit)
- Firefox 90.0 (64-Bit)
- Firefox Quantum 68.9.0esr (64-Bit)
