### ISSUE TITLE
Fix e2e tests

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#438]
Since jenkins update the e2e tests do not work anymore. Starting cypress from jenkins is not possible.

Error:
`/var/lib/jenkins/.cache/Cypress/4.12.1/Cypress/Cypress: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

Perhaps updating cypress to the newest version would fix the issue.

**Comment by dptolle** [comment]
@afalenski @GerberI  I opened an IT Ticket to install the missing dependencies.
