### ISSUE TITLE
Edit data in online Excel view and validate against js validator

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#44]
As a MIBI User I want to edit already uploaded and validated excel data in the browser (Handsontable) and validate them against the js validator.

**Comment by draaw** [comment]
please take care of date format. it should be german
See e.g. in validate_dt.jsp for the function XLSX.utils.sheet_to_json and use parameters -> dateNF:'dd"."mm"."yyyy', blankrows:false,

**Comment by draaw** [comment]
Is it possible to reduce the font size to 12?

**Comment by draaw** [comment]
it would be great if the button "Validate data" could be visible always. Maybe as part of the MiBi-Portal header, which should also not be scrollable?

**Comment by birgitlewicki** [comment]
implemented and deployed

**Comment by draaw** [comment]
Nearly perfect
The header of Handsontable "hides" behind the header of the portal after doing some scrolling down

**Comment by birgitlewicki** [comment]
implemented and deployed

**Comment by draaw** [comment]
looks really good ;-)
Some very tiny thing left: the scrollbar now hides behind the header of handsontables

**Comment by draaw** [comment]
it seems to be OS related. In MacOsX the vertical scrollbar is hidden behind the header. In Windows it is not, independent of the browser.
Maybe a ticket for the handsontable community should be written.
For my taste: I would prefer the vertical scrollbar starting at the first row

**Comment by draaw** [comment]
E-Mail exchange with Handsontable maintainers result in: "There is no easy fix for this. Changes in our layers rendering is our long term goal but are time consuming and expensive and are not scheduled yet."
Therefore we will forget about it for now as it is not that critical.

**Comment by GerberI** [comment]
Obsolete
