### ISSUE TITLE
Rename Epi-Lab to Mibi-Portal

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#46]
The name Epi-Lab is the Lab name. The first portal of the application is called Mibi-Portal

DeveloperNote: is it possible / does it make sense to define the Portal name as a variable?

**Comment by dptolle** [comment]
Implemented & pushed to develop: requires deployment to proceed.

**Comment by draaw** [comment]
the email sender address still is
edpilabteam epilab@epilab.bfr.berlin
the domain cannot be changed, but the other parts should

**Comment by dptolle** [comment]
@birgitlewicki : Hi, could you please change the config value 'mail.fromAddress' in the qa.json file on the QA machine to '"mibiportalteam <mibiportal@epilab.bfr.berlin>'

**Comment by draaw** [comment]
The email sender for password recovery is edpilabteam <epilab@epilab.bfr.berlin>
'mail.fromAddress' should be used here as well
