### ISSUE TITLE
Scroll positions persists during page change

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#460]
The scroll positions is persisted during page change.

1. Go to "faq" page
2. Scroll down
3. Go to "datenschutz" page
4. The "datenschutz" page is scrolled too

A newly opened page should displayed with scroll position at the top and not with a scroll position from another page.

Note: Check which pages are affected by the bug.
=> Only pages not handling scrolling on their own are affected. So: only scrollable parent elements of the router-outlet are affected.

**Comment by GerberI** [comment]
Angular scrolling mechanism could not be used here because it works only for the top view. Because we have a header and a footer scrolling behavior had to be implemented manually. So i hooked into the page transition animation to reset scrollbar just before the new page is shown.

**Comment by GerberI** [comment]
Additionally done: Fixed bug of faq sections be visible expanded for a short time when navigating to faq page. Now their is another bug visible: The faq sections are rendered a little bit higher for a short time (i have no idea why).

**Comment by GerberI** [comment]
See also: #483

**Comment by afalenski** [comment]
The GDPR page is not scrolled down anymore when opening the page after having scrolled down on th FAQ page.
The new buggy visualisation is not nice, but not disturbing too much.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Google Chrome Version 102.0.5005.115 (Offizieller Build) (64-Bit)
- Firefox 91.10.0esr (64-Bit)
