### ISSUE TITLE
Exchange BfR logo

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#463]
As a MiBi-Portal product owner I would like the MiBi-Portal to show the current BfR logo. Please exchange the old logo with the new one (see attachment in email to IG on 31.05.2022)
Please use the same size as in the current logo. PNG is preferred, but as the current one is a GIF, both types were provided.

**Comment by GerberI** [comment]
- Changed logo at home-page
- Changed logo in pdf sample sheet
- Changed FAQ

**Comment by afalenski** [comment]
The new logo is visible. Strange, that it appears clear in Firefox but a little blurred in Chrome.
Firefox:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/8b2d1493-1abb-422f-9afd-6299047f493a)

Chrome:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/48d4b5fc-d7aa-4d14-ba92-9bf439bb2c50)
Done.

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Google Chrome Version 96.0.4664.110 (Offizieller Build) (64-Bit)
- Firefox 91.7.0esr (64-Bit)
