### ISSUE TITLE
Adjust MiBi-Portal to BfR corporate design

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#469]
As a product owner I want the portal to be recognised as a BfR service and thus the colours and (if possible) the fonts should resemble the current BfR style.

Corporate Design:
https://intranet.bfr.bund.de/cocoon/portal/portallink?doctype=Navknoten&id=2973

RGB(0, 56, 105)
- "MiBi-Portal" headline on home screen
- Dark blue navigation bar
- All links 
- Top border of footer
- Button font and symbols in light blue navigation bar
- Text and symbols in front of light blue background (light blue navigation bar, selected button in dark blue navigation bar)

RGB(186, 216, 233)
- Light blue navigation bar
- Selected button in dark blue navigation bar

- From the new BfR corporate design colour palette choose a lighter grey for the NRL column than is currently used in order to differentiate the column from table rows and column header cells.

Persisted orders: If the user hovers over a row with the mouse, the row turns light blue (like the color from the second menu bar, RGB(186, 216, 233)) and the text changes to dark blue (RGB 0, 56, 105, #003869). The row can be selected via left mouse click.

If possible: Change font to Roboto (to be discussed: Roboto medium or Roboto regular)

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/469?planning-poker) with ZenHub @birgitlewicki @GerberI @ruegenbfr

**Comment by GerberI** [comment]
Additionally done:
Design
    - Used new BfR colors
    - Redesigned all forms
    - Redesigned faq page
    - Used Roboto as standard font
    - Redesigned nav-bar
    - Changed button styles in dialogs
    - Thick avatar border in all browsers

    Common
    - Removed html tag based content projection
    - Refactored dialog
    - Refactored analysis stepper
    - Fixed missing admin activate error handling
    - Switched to material-icons from fontsource
    - Added "cypress/examples" to gitignore
    - Fixed missing "warning" banner type
    - Removed unused colorType from user actions
    - Fixed tooltipster border styles

    Faq
    - Moved faq from "/content/faq" to "/faq"
    - Moved faq components from content to main module
    - Refactored faq components
    - Fixed scroll bug in faq
    - Adjusted faq json format
