### ISSUE TITLE
Persist: Add table for previous orders 2

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#471]
As a MiBi-Portal user I would like to see orders when I click on the button "Bisherige Aufträge".

As a follow-up of the research ticket (#467): Use material UI table or MiBi-Portal table
=> Use angular material UI table with single-center-card layout (done in #467).

Use mock data in this ticket.

- Both columns are sortable; by default, the column „Datum / Zeit“ is sorted descending; internally, the column is sorted by YYYYMMDD HH:MM to be able to sort by date and time.
- If the user hovers over a row with the mouse, the row turns light blue (like the color from the second menu bar, RGB(186, 216, 233)) and the text changes to dark blue (RGB 0, 56, 105, #003869). The row can be selected via left mouse click.

Dev-Note:
- ~Try to use the material ui default data source provider class as input for the order-list to apply sort functionality. Note: This will violate our plain object as input data rule, but is the recommended solution by angular material ui docs.~ => Used angular material default data source provider only internally.
- Add model for defining the data of the order-list. The model should contain an id field not visible in the table for now (for click event handling).
- Add click event handler returning the clicked row data object.
- ~Add logic in container to create data source from a mock observable data stream.~
- Use transparent overlay for hovered / selected rows to use same coloring as in samples-grid.
- Refactor: Move common hover / selection and ui colors from samples-grid to global styles. Perhaps move some of the global styles to shared.

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/471?planning-poker) with ZenHub @birgitlewicki @GerberI @ruegenbfr

**Comment by GerberI** [comment]
@afalenski 
I used the same colors as in our samples-grid for hovering and selection in #467. I hope this is fine for the final solution. If you like, you can adjust the ticket text accordingly.

**Comment by afalenski** [comment]
- [x] Sorting by filename works fine.
- [x] Date/time column is sorted descending by default.
- [x] If the user hovers over a row with the mouse, the row turns light blue. Adaptation to BfR CI will be done in a separate ticket.
- [ ] The date / time column in the table is sortable; unortunately, there were not several entries with the same date but different times to test whether sorting via date AND time worked. This is why I changed date and time in one row via the browser dev tools and sorted again. Unfortunately, the sorting did not work as expected, because the 10.10.1992 15:33:27 should be the last row when sorted ascending (see first examples below). A second test gave the impression, that the table has an internal sorting that does not react to changes in the client. If this is the case, I need a list of dates in which at least one date occurs 3 times with different minutes between 2 times and different seconds between 2 times, like 10.10.1992 with the times 15:33:27, 15:33:26 and 15:32:26.
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/6eb54d0d-b7cb-495d-bf23-e56418cd7657)
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/34aa5972-379a-492f-b782-295001baa899)
Please have a look at the sorting of date and time.

**Comment by GerberI** [comment]
I added more mock data. Also i presorted the table, so that orders with the same name are sorted by time too. Orders with the same time are not sorted by name: material table does not support sorting by multiple columns. But i think this use case will not happen, but we could reject sending multiple sheets in the same second, then we have some dos-protection.

**Comment by afalenski** [comment]
Thanks. Works fine. 
Done
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Browsers:
- Firefox 91.10.0esr (64-Bit)
