### ISSUE TITLE
Adjust RegEx for AVVData number for Lower Saxony

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#474]
As a user from a lab in Lower Saxony I would like the MiBi-Portal to give a warning only if the format is incorrect.

The structure of the AVVData number has changed. Please use the new RegEx rule:
Old: "[0-9]{4,5}"+yy+"[0-9]{4,6}"
New: "[0-9]{2}"+"-[0-9]{3}"+yy+"-[0-9]{3,7}"

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/474?planning-poker) with ZenHub @bfrgottscma @birgitlewicki @ruegenbfr @GerberI

**Comment by GerberI** [comment]
@afalenski 
Is the "only lower saxony" condition already implemented for the old regexp?

**Comment by afalenski** [comment]
- Logging in with a NI account, a correct AVVData sample number does not produce a warning; a AVVData number in the old format does.
- Logging in with a non-NI account, the NI AVVData sample numbers (old an new formats) produce a warning.
Done.
