### ISSUE TITLE
Persist: Refactor samples-grid to be configurable

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#481]
The samples-grid will be reused by the new previous order sample-viewer. So it's view model has to be configurable and needs to be refactored.

Dev-Note:
- Split the now constant view model definition into a public interface and a constant model definition for the respectable containers (now only samples-editor, later samples-viewer).
- Only useful things in the model should be configurable (cell-templates, read-only mode or visible cols). (Keep in mind that the configurable samples-grid should still only show samples and so should have a slim interface.)
- Adapt the samples-editor container to use the new configuration to display the samples-grid.

**Comment by GerberI** [comment]
For performance reasons i made the samples-grid more abstract. It uses now the same data structure as the data-grid for input. This makes the samples-grid freely configurable but puts more coding affords to components using the samples-grid (e.g. caching functionalities, data mappings).

@afalenski 
If you like you can test the whole samples-editor: Performance, Editing, Validation messages, etc... But in general i did not touched any logic, so it should work fine.

**Comment by afalenski** [comment]
- Editing works as usual.
Performance: 
- 100 rows: 1st test Good
- 1000 rows: Okay; loading takes 17 seconds plus 1-2 seconds white browser (only menu bar and footer visible); speech bubbles pop up a little more reluctantly, especially when one cell shows 3 speech bubbles; but the upload of such a big file is unlikely and the performance ist still okay.
- [ ] 100 rows: 2nd test (after the 1000 rows test) showed during loading the old dataset in transparent with a "wait circle" visible; after 3 seconds the dataset area became white and no data was loaded; only menu bar and footer were visible. This is reproducible! Please fix.
[https://app.zenhub.com/files/103999212/6f36[https://app.zenhub.com/files/103999212/6a409f0d-9924-4571-b361-e3f8b0932d07/download](https://app.zenhub.com/files/103999212/6a409f0d-9924-4571-b361-e3f8b0932d07/download)8d2a-4772-4fb0-9f73-65364f528b22/download](https://app.zenhub.com/files/103999212/6f368d2a-4772-4fb0-9f73-65364f528b22/download)

______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
- Einsendebogen-v15_TEST.xlsx
- MiBi-TEST_Error-Codes_B_ZSP.xlsx
- Mibi-Portal-Testdatei100.xlsx
- Mibi-Portal-Testdatei1000.xlsx

Browsers:
- Firefox 91.10.0esr (64-Bit)

**Comment by GerberI** [comment]
I could not reproduce the issue with firefox, but i use the newest version. Can you test if the issue is still there on the productive system with firefox 91.10?
Another thing is that the scroll position remains after loading. This should be fixed in a new ticket. A simple solution could be to clear the data before the new sheet gets loaded. Then the user sees an empty table during loading. Perhaps the issue you mentioned will be fixed too with this.

**Comment by afalenski** [comment]
Yes, this problem also occurs in the productive MiBi-Portal using Firefox 91.10. Display of speech bubbles seems to be equally fast in both MiBi-Portal versions.
________________
Tested with
Machine: BfR-Laptop

OS: Windows 10

Datasets:
- Mibi-Portal-Testdatei100.xlsx
- Mibi-Portal-Testdatei1000.xlsx

Browsers:
- Firefox 91.10.0esr (64-Bit)
