### ISSUE TITLE
Update angular to v13

### ISSUE THREAD

**Issue by GerberI** [SiLeBAT/mibi-portal-client#499]
Angular has to be updated to v13.

- Some packages require typescript 4.4, which is incompatible to Angular v12.

See also:
https://update.angular.io/?l=3&v=12.0-13.0
https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296
https://v13.ngrx.io/guide/migration/v13

**Comment by afalenski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MiBi-Portal-5a817089b72527484e410a5a/issues/SiLeBAT/mibi-portal-client/499?planning-poker) with Zenhub @bfrgottscma @GerberI @ruegenbfr

**Comment by birgitlewicki** [comment]
Updated and merged into develop, but not yet deployed on qa

**Comment by birgitlewicki** [comment]
Update done and is tested in ticket https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-portal-client/523
