### ISSUE TITLE
Uploading a second Excel file shows the results of the first Excel file after clicking on "Go to Validator"

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#50]
IST: Uploading a second Excel file shows the results of the first Excel file after clicking on "Go to Validator"
SOLL: Uploading a second excel should not display the results of the first excel, but instead an Loading indicator followed by the result.

**Comment by draaw** [comment]
It seems as if it is a kind of a refreshing problem. Anyhow, the result of the first validation should not show up

**Comment by birgitlewicki** [comment]
fixed by mpc #44
