### ISSUE TITLE
Make customer email text more prominent

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#508]
As an NRL lab technician receiving MiBi-Portal emails I would like to see more easily if a portal customer has added an email text. Currently, the standard text is formatted in the same way as the text added by the customer and can be overlooked.

Idea: If there is a customer message, format this in bold type.

**Comment by GerberI** [comment]
Additionally done:
- The hint in the user and BfR mails, regarding the user comments, is now only shown if there are any comments.
- The comments are now aware of line breaks. Especially the mibi-portal already sent message is now shown in it's own line, separated by the user comment.

**Comment by afalenski** [comment]
Ha, good idea to put the warning also in bold type!
The email looks just as I imagined, great!
Done.
