### ISSUE TITLE
Feedback in case of wrong file type or file too large 

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#51]
As a portal user i would like to have a feedback what is wrong with the files I want to upload

**Comment by dptolle** [comment]
Feature completed & on develop - please deploy

**Comment by draaw** [comment]
Please change:
"File is too large: Files should be less than 2Gb" -> "File is too large: Files should be less than 2 MB"

**Comment by draaw** [comment]
Additionally: the error message remains, when uploading the next valid file
