### ISSUE TITLE
If ADV9 is given but Zip and City not, put both into XLSX

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#514]
As an NRL user who needs to know the place from where a sample was taken, I would like to see the city (Ort) and ZIP (PLZ) in the Excel sheet if the ADV9 code was given.

Note: If PLZ and Ort are both empty and the ADV9 code is present, fill the PLZ cell and the Ort cell of the sample dataset with the text from the ADV catalogue, but only in the Excel sheet which is sent to the NRLs. Do not show it in the client and do not put it into the PDF the uploading user gets.

Column "Ort der Probe­nahme (PLZ)": Postleitzahl
Column "Ort der Probe­nahme (Text)": Bezeichnung
(see CSV file in the portal or the PDF at https://katalogportal.bvl.bund.de/katalogportal/KatalogExportieren.html?catalogId=37&versionId=2551)

Before:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/0b79c35e-3a40-4a87-ab5c-48fdce4eec9e)

After:
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/e1b463a6-b8ba-4ddd-a22a-e16d65370530)

**Comment by birgitlewicki** [comment]
Implemented as requested.
If only the ADV9 code is given the plz and city (taken from the ADV9 catalog entry) are present now only in the excel sheet for the nrl.

**Comment by afalenski** [comment]
If a correct ADV9 code is given and both PLZ and place cells are empty,
- PLZ and place are not shown in the client.
- PLZ and place are added to the Excel file which is sent to the NRL.
- PLZ and place are not added to the Excel file which can be exported via the client.
- PLZ and place are not added to the PDF file which is sent to the user.
- PLZ or place are not added or overwritten if the other was given.
All fine.
Done
