### ISSUE TITLE
Add new ADV catalogs

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#519]
As a user I would like the MiBi-Portal to support the latest ADV catalogs.

Please exchange the current catalogs against the new ones (see email 06.06.2022@10:54).

**Comment by afalenski** [comment]
Looks good. Test sheets are checked, validation is correct.
Please push to productive portal

**Comment by birgitlewicki** [comment]
Hotfix is pushed to production system.

**Comment by afalenski** [comment]
Great, works fine.
Done.
