### ISSUE TITLE
Account activation: Change toaster and message

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#524]
As a user I think I would like to know what to do after I have confirmed my email address. Currently the text is misunderstandable making me think I can directly login and do not have to wait for admin activation. Change texts.

- Change the following email and toaster texts for both the test MiBi-Portal (epilab-dev) and the productive MiBi-Portal (omit "-QA" in texts for the productive portal).

**Toaster message directly after registration**
Toaster old: "Bitte aktivieren Sie Ihren Account: Eine E-mail mit weiteren Anweisungen wurde an [EMAIL] gesendet"
Toaster new: "Bitte bestätigen Sie Ihre E-Mail-Adresse: Eine E-Mail mit weiteren Anweisungen wurde an [EMAIL] gesendet"
_____________________________________________________________
**First email to user directly after registration**

Subject old: "Aktivieren Sie Ihr Konto für MiBi-Portal"
Subject new: "Bestätigen Sie Ihre E-Mail-Adresse"

-------------------------------------------------------------
Email text old: 
"Liebe(r) [NAME],

Sie haben sich für ein MiBi-Portal-Konto registriert.

Bitte benutzen Sie den Link unten, um Ihr Konto zu aktivieren. Dieser Aktivierungslink ist nur für die nächsten 24 Stunden gültig."
Button text: "Aktivieren Sie Ihr Konto"

"Die Aktivierung Ihres Kontos muss durch den Administrator des MiBi-Portals bestätigt werden. Sie erhalten nach erfolgter Freischaltung eine weitere Benachrichtigung.

Nach der erfolgreichen 2-Schritt Aktivierung können Sie sich am MiBi-Portal anmelden.

Sicherheitsbezogen: Diese Anfrage wurde mit Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 gesendet. Wenn Sie sich nicht für einen MiBi-Portal-Account registriert haben, ignorieren Sie bitte diese E-Mail oder Kontaktieren Sie den Support, wenn Sie Fragen haben.

Das MiBi-Portal Team

Wenn Sie Probleme mit dem obrigen Link haben, kopieren Sie die untenstehende URL und fügen Sie sie in Ihren Webbrowser ein."

-------------------------------------------------------------
Email text new: 
"Liebe(r) [NAME],

Sie haben sich für ein MiBi-Portal-Konto registriert.

Bitte benutzen Sie den Link unten, um Ihre E-Mail-Adresse zu bestätigen. Dieser Link ist nur für die nächsten 24 Stunden gültig."
Button text: "E-Mail-Adresse bestätigen"

"Die Aktivierung Ihres Kontos muss durch den Administrator des MiBi-Portals bestätigt werden. Sie erhalten nach erfolgter Freischaltung eine weitere Benachrichtigung.

Nach der erfolgreichen 2-Schritt Aktivierung können Sie sich am MiBi-Portal anmelden.

Sicherheitsbezogen: Diese Anfrage wurde mit Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 gesendet. Wenn Sie sich nicht für einen MiBi-Portal-Account registriert haben, ignorieren Sie bitte diese E-Mail oder Kontaktieren Sie den Support, wenn Sie Fragen haben.

Das MiBi-Portal Team

Wenn Sie Probleme mit dem obrigen Link haben, kopieren Sie die untenstehende URL und fügen Sie sie in Ihren Webbrowser ein."
_____________________________________________________________
**MiBi-Portal toaster message in the browser after confirming the email address**
Headline old: "Konto aktiviert"
Headline new: "E-Mail-Adresse bestätigt"

-------------------------------------------------------------
Text old:
"Sie haben Ihr MiBi-Portal-QA Konto aktiviert.

Sobald der MiBi-Portal-QA Administrator Ihr Konto freigeschaltet hat, können Sie sich einloggen. Sie erhalten nach erfolgter Freischaltung eine Benachrichtigung."

-------------------------------------------------------------
Text new:
"Sie haben Ihre E-Mail-Adresse bestätigt.

Sobald der MiBi-Portal-QA Administrator Ihr Konto freigeschaltet hat, können Sie sich einloggen. Sie erhalten nach erfolgter Freischaltung eine Benachrichtigung."

**Comment by birgitlewicki** [comment]
Probably duplication of https://app.zenhub.com/workspaces/mibi-portal-5a817089b72527484e410a5a/issues/gh/silebat/mibi-portal-client/513

**Comment by afalenski** [comment]
Done.
