### ISSUE TITLE
Adjust the position of the word "Labor" in the PDF version of the Einsendebogen

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#525]
As a MiBi-Portal admin I would like the PDF to have a tidy layout and thus the word "Labor" should start at the same position as the words "Bundesinstitut" and "Diedersdorfer"

2 things to change:
- The word "Labor" should start at the same position as the words "Bundesinstitut" and "Diedersdorfer"
- The width of the box containing the lab name should be enlarged to the left so that the distance to the word "Labor" stays the same as before. Thus it should also be possible to display the lab name "NRL koagulasepositive Staphylokokken einschließlich Staphylococcus aureus" in one row (currently: 2 rows)
![grafik.png](https://images.zenhubusercontent.com/5a854eea4b5806bc2bc70715/16766c6f-7489-408f-a687-a59129225f25)

**Comment by birgitlewicki** [comment]
Implemented and deployed on qa.

**Comment by afalenski** [comment]
- "Labor" is now left-aligned.
- The full name of NRL-Staph can be displayed in one row in the PDF.
Done.
