### ISSUE TITLE
Info toaster

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#527]
As a user I would like to be informed about changes in the MiBi-Portal.

- Add a toaster which is shown directly after login, regardless from which MiBi-Portal state the login starts (login with or without uploaded data).
- The toaster should only disappear when the user clicks "Schließen".
- Toaster text: "Zu Ihrer Information: Ab sofort erhalten sie die E-Mail mit dem Probenbegleitschein (PDF) von der E-Mail-Adresse 'mibi-portal@bfr.berlin'."
- Show the email address as plain text, not as clickable email address. Users should not use this email address.
- The toaster will be shown at every login until it is deactivated by the developer.

[Info Toaster](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEZKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e4047aa2a3f20994b2ffacc6e7f29ca638d7cf3/mpc527_InfoToaster.png)

**Comment by birgitlewicki** [comment]
Implemented as requested and deployed on qa.
Please test

**Comment by afalenski** [comment]
- The toaster appears directly after the login, regardless whether the user starts with or without uploaded data.
- The toast disappears when clicking the button "Schließen" or when changing the page. This is contrary to the ticket text, but it is okay for now.
- The email address is in plain text.
- **Bug:** When trying to login and entering a wrong password, the new info toaster is shown, not the 'wrong password toaster'. The info toaster should be visible AFTER the successful login.

**Comment by birgitlewicki** [comment]
Bug is fixed:
The info toaster is visible only after a successful login.
If the login fails the 'wrong password' toaster is visible.

**Comment by afalenski** [comment]
Done.
