### ISSUE TITLE
Export of excel sheet does not work on qa

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#538]
Clicking the client button "Exportieren" results in an error message displayed in the toaster:
"Es gab einen Fehler beim Exportieren der Datei"

**Comment by birgitlewicki** [comment]
Fixed.
Excel sheet can be exported again.

**Comment by afalenski** [comment]
- Excel sheet is exported and contains sample data from uploaded file.
- Auto corrections are coloured in turquoise.
**Bugs:** 
- As lab methods "Impfstammidentifikation" is ticked. The NRL-AR does not offer to do such a method and does not offer to do so in the wizard. The MiBi-Portal removes all methods that are not offered by the lab. Please remove the "x". 
- "sonstiges" is ticked (correct), but at the wrong position (see screenshot of uploaded sheet)
- "sonstiges" is ticked (correct), but the text is missing.
- The text "Vergleiche mit humanen Isolaten" is missing, it is not ticked (the "x" is missing) and the message is missing.

Uploaded:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMERRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e21666e7de0fa227dd8d5a6233a89a55deeea76f/grafik.png)

Exported:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBei9RQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea9168de19d084f322da945aa91d6e6f33e705d5/grafik.png)
Please fix.

**Comment by birgitlewicki** [comment]
Fixed as described:

- The cells were shifted due to changes in the analysis methods of the new excel sheet v17.This is corrected now.

Not yet fixed:

- We have still the bug that the text in "sonstiges..." and "Vergleiche mit humanen Isolaten" is not imported correctly into the Mibi-Portal and therefore does not appear in the exported excel sheet. As stated in the comment this bug will be handled by another ticket.

**Comment by afalenski** [comment]
- Excel sheet is exported and contains sample data from uploaded file.
- Auto corrections are coloured in turquoise.
- Methods are correct for NRL-AR and NRL-Staph.
Done.
