### ISSUE TITLE
Show Umlaute correctly in ADV portal

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#541]
- Upload an Einsendebogen containing Umlaute or ß in the name. 
The letters are replaced by strange looking other letters.
Example:
Excel file name: mpc_Einsendebogen-v17_Späßchen über UmlauteÖöÜÄ
Displayed: mpc_Einsendebogen-v17_SpÃ¤Ãchen Ã¼ber UmlauteÃÃ¶ÃÃ.xlsx 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejdnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b42158b823b483859c7b8ae6addefd43110c55bf/grafik.png)

Fix in
- Client
- Excel sent to BfR lab
- PDF sent to user

**Comment by birgitlewicki** [comment]
German Umlaute are now shown correctly in the ADV portal client.

**Comment by afalenski** [comment]
- Filename in client, in exported Excel, in LIMS Excel and in PDF is fine and contains special characters.
Done.
