### ISSUE TITLE
Exported Einsendebogen does not contain text at "sonstiges" and "human..."

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#543]
- Upload an Einsendebogen v17 containing text at "sonstiges" and at "Vergleiche mit humanen Isolaten".

Bugs:
- The text is not there. 
- The "x" is missing although it was set in the uploaded Einsendebogen.
- If the Einsendebogen contains only pathogens for one BfR lab, these texts should also be shown in the wizard, which is not the case.

Please fix.

**Comment by birgitlewicki** [comment]
Implemented as following:

- When uploading an Excel sheet v17 with one or more samples belonging to one single nrl that have text in the "Erreger" column the yellow text at "sonstiges" and at "Vergleiche mit..." appears in the exported Excel sheet.
- In the case that the "Erreger" column contains the pathogen code from the 324 catalog the text of the yellow boxes does not appear in the exported Excel sheet.. The same "feature" exists on the productive system.

**Comment by afalenski** [comment]
- The text at "Sonstiges" and "Vergleiche mit humanen Isolaten" is from the uploaded Einsendebogen is also in the exported Einsendebogen containing only pathogen texts for one NRL.
- The "x" is in the exported Einsendebogen.
- Texts at "Sonstiges" and "Vergleiche mit humanen Isolaten" are shown in the wizard.
- If there are pathogens for more than one BfR lab in the uploaded Einsendebogen, there is no text at "Sonstiges" or "Vergleiche mit humanen Isolaten", neither in the wizard, nor in the exported Einsendebogen (good).
Done.
