### ISSUE TITLE
Reduce number of characters in wizard and add counter

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#544]
As an NRL user I would like to be able to always read the text at "Sonstiges" and "Vergleiche mit humanen Isolaten" in a printout.

- Add counter to both text boxes in wizard (if possible, reuse the counter we already have in the last "Senden" dialogue)
- Allow 130 characters. Before setting this number as final, check in PDF whether also there 130 characters fit in (has other font and font sizes than the Einsendebogen Excel). Use for the test these two texts:

Text 1 (130 chars):
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam

Text 2 (130 chars):
Dies ist ein Test von Hans. Keine echten Daten. Nicht fürs LIMS bestimmt. Hans testet hier die Zahl der Zeichen, die in eine Excel

**Comment by afalenski** [comment]
- Counter works
- Max 130 chars is true
- Text at "Sonstiges" fits into Excel sent to NRLs

Text at "humane Isolate" could not be tested, old layout; will be tested in mpc546.
Test in PDF was not possible because the layout is currently being changed (mpc545). Will be tested there.
Done.

**Comment by birgitlewicki** [comment]
Implemented:
- If the uploaded Excel sheet contains text at 'sonstige' and/or 'compare Human...' that is longer than 130 characters it is truncated and the wizard shows only the first 130 characters.
- the text is temporarily cached if the user ticks the checkboxes

**Comment by afalenski** [comment]
- Now, also texts longer than 130 characters uploaded via Einsendebogen are truncated.
- When accidentally ticking a box at "Sonstiges" or "Vergleiche mit humanen Isolaten", the text is stored; ticking the box again, the text is still available.
- When un-ticking the box and sending, the text is not in the LIMS Excel nor in the PDF (good!)
- When un-ticking the box, sending and then ticking the box, the text is lost (good).
- Unfortunately, the example texts with 130 characters were not representative. Of a new text, only 120 characters fit into the Excel cells at "Sonstiges" and "Vergleiche mit humanen Isolaten". Character reduction to 120 will be done in a later ticket.
Done.
