### ISSUE TITLE
Correct column headlines in client

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#550]
As a user I would like to see the identical column headlines in the client as in the Einsendebogen.

- Replace "AVV DatA-TeilprobenNr." by "AVV DatA-Teilproben-Nr." (with hyphen before "Nr.")
- Replace "Tiere/Matrix (Text)" by "Tiere / Matrix (Text)" (empty space before and after the slash)

**Comment by birgitlewicki** [comment]
Implemented as requested

**Comment by afalenski** [comment]
Done.
