### ISSUE TITLE
Remove yellow ZoMo warning

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#551]
As a user I would like to see only legitimate warnings. As data is not checked for ZoMo, the ZoMo warning (error 49) should be deactivated, so that there are no ZoMo warnings anymore.

**Comment by birgitlewicki** [comment]
The ZoMo constraints for error 49 are commented out currently.
As soon as we will have a valid ZoMo plan these comments need to be removed.

**Comment by afalenski** [comment]
Done.
