### ISSUE TITLE
Change validation error texts

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#552]
As a user I would like to get an error message for both animals and foods. The current message only contains food in the text.

Please pay attention to the comment in column H in file validationerrors_20231207.xlsx sent by AF on 07.12.2023
- Replace text for error 37:
Old: "Bitte geben Sie eine Matrix an!"
New: "Bitte geben Sie eine Matrix, ein Tier oder beides an!"

- Delete error 32:

- Replace text for error 34:
Old: "Bitte geben Sie den AVV DatA-Code für die Matrix an! (Pflicht bei ZoMo)."
New: "Bitte geben Sie den AVV DatA-Code aus dem Tier- und/oder Matrix-Katalog an! (Pflicht bei ZoMo)." (warning in both columns)

**Comment by birgitlewicki** [comment]
Implemented as requested

**Comment by birgitlewicki** [comment]
fixed:
- error 34
- strange autocorrection

**Comment by afalenski** [comment]
- If ZoMo and no matrix is given, error text 34 is only shown in both Tier and Matrix code cells, not anymore in the Tier / Matrix (Text) cell.
- No strange autocorrection was visible.
Done.
