### ISSUE TITLE
Rename MiBi-Portal for ADV in MiBi-Portal ADV

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#553]
As a user I would like to quickly see that I upload data in the MiBi-Portal for ADV codes.

Rename "MiBi-Portal" in "MiBi-Portal ADV"
- In the blue menu bar in the top left
- On the startpage in the big headline

<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2hrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fe84e679b64cf6e2947630442bf6de4e24c6882/grafik.png" alt="grafik.png" />

</br>
<img width="420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97d9dde232679ecb380b9f3b689f8f1a822f124d/grafik.png" alt="grafik.png" />

**Comment by birgitlewicki** [comment]
The MiBi-Portal is renamed and deployed on nolar.
The Fix is not deployed on the current production system.
