### ISSUE TITLE
Autotext changes to be done in the client

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#554]
As a user I would like the autocorrections (automatically translated codes into text) to look similar to the PDF version:

- [ ] If the user has uploaded a code and in the text cell an individual text, the AVV MiBi-Portal should write the following into the text cell (see below). If there is no individual text, omit "User: "; if there are text columns for two code columns, omit the introducing text, e.g.: omit "Tier: " if no code from AVV DatA catalogue 339 was uploaded
- [ ] If there is only one code column, omit the prefix text when there is no user entry; e.g. for column "Betriebsart" and "Ort".
- [ ] Separate texts by full stop.
- [ ] Type the texts "User:", "Ort:", "Tier:", "Matrix:", "Kontroll-P:", "Unters.-Grund:" and "Betrieb:" in bold face so that the user can easily differentiate between own text and code translations. The user text or the code translation should be shown in normal font, not bold.
- For column "Ort der Probenahme (Text)": "User: "[Text uploaded by user]". Ort: "[Text at ID 1401 from AVV DatA catalogue 313]
- For column "Tiere / Matrix (Text)": "User: "[Text uploaded by user]". Tier: "[Text from AVV DatA catalogue 339]". Matrix: "[Text from AVV DatA catalogue 319]
- For column "Kontrollprogramm / Untersuchungsgrund (Text)": "User: "[Text uploaded by user]". Kontroll-P: "[Text from AVV DatA catalogue 322]". Unters.-Grund: "[Text from AVV DatA catalogue 326]
- For column "Betriebsart (Text)": "User: "[Text uploaded by user]". Betrieb: "[Text from AVV DatA catalogue 322]"

These features are already in place in the client and are listed here for completeness to describe the new client look.
- [x] Automatically translated AVV DatA texts should NOT be shortened (in contrast to PDF).
- [x] If the user has uploaded only a code, the PDF should contain simply the respective AVV DatA text.
- [x] If the user has uploaded a code and in the text cell the respective text translation (100% identical to the code translation including the facette catalogue name), the AVV MiBi-Portal should leave it as it is and - as this is no autocorrection - this cell should not be highlighted in blue.

**Comment by birgitlewicki** [comment]
Autocorrections are added.
Please test intensively if all text exchanges are done in a consistence manner.

**Comment by birgitlewicki** [comment]
As discussed all autocorrections are removed except the one for the pathogen.
We will discuss a new concept for how autocorrections can be realized in consideration of having several validation cycles and that the user can edit the text and code fields. This will be done in a new ticket.
