### ISSUE TITLE
Delete API endpoint and link in footer

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#555]
As a user I would like to see only information I can use.

- Delete API endpoint in MiBi-Portal AVV. It has not been adapted to the new code, yet.
- Delete link "API-docs" in footer and spread the rest of the footer links evenly over whole screen width.

Note: Info on API in FAQ will be deleted, but is topic in another ticket.

**Comment by birgitlewicki** [comment]
- The API docs link in the client is removed
- The API docs endpoint is not reachable anymore

**Comment by afalenski** [comment]
Done.
