### ISSUE TITLE
New validation errors

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#556]
As a MiBi-Portal creator I would like to inform the users what autocorrections mean or where the text comes from.

Use the validationerrors Excel file sent by AF on 19.12.2023

- 103: Change text
Old: "Tier- / Matrix-Code erkannt. Entsprechender Text wurde aus AVV DatA-Katalog Nr. 339 / 319 generiert."
New: "Code für Tier / Matrix erkannt. Entsprechender Text wurde aus AVV DatA-Katalog Nr. 339 / 319 eingefügt".

- Put new messages 106, 107 and 108 in place.

**Comment by birgitlewicki** [comment]
New validation messages added and one changed.

**Comment by afalenski** [comment]
I cannot test this as no autocorrections are in place in these columns.
Done.
