### ISSUE TITLE
Do not show link to Einsendebogen in AVV-Portal

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#557]
As a user I do not want to see useless links. The link at Probendaten\Excel-Vorlage currently links to Einsendebogen-v16.xlsx which cannot be used in the AVV-MiBi-Portal.

- Do not show the link "Excel-Vorlage" in the light blue menu bar. 
Comment: As soon as the link to the new Einsendebogen exists, the link will be needed again.

<img width="284" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2w0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deebcb5f9bb0db7809a4d4b3a192b3b2e98384b7/grafik.png" alt="grafik.png" />

<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3Q0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02fa57f7be7143b4b6e2aa459a9258d1a4e3e692/grafik.png" alt="grafik.png" />

**Comment by birgitlewicki** [comment]
The link to the Einsendebogen in AVV-Portal is removed
