### ISSUE TITLE
Change text on Startpage MiBi-Portal ADV

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#558]
Exchange text in the first two paragraphs on Nolar, leave the rest of the text as before.

**Old:**
Sie befinden sich auf dem neuen Datenaustausch-Portal der mikrobiologischen nationalen Referenzlabore des Bundesinstituts für Risikobewertung (BfR).

Hier haben Sie die Möglichkeit sich zu registrieren und nach dem Einloggen Ihre im Probeneinsendebogen eingetragenen Daten hochzuladen, zu validieren und an das BfR zu senden. Der Probeneinsendebogen ist unter Probendaten \ Excel-Vorlage verlinkt und steht auf der gewohnten BfR-Seite zur Verfügung. 

**New:**
Sie befinden sich auf dem Datenaustausch-Portal der mikrobiologischen nationalen Referenzlabore des Bundesinstituts für Risikobewertung (BfR).

Hier haben Sie die Möglichkeit sich zu registrieren und nach dem Einloggen Ihre im Probeneinsendebogen eingetragenen ADV-codierten Daten hochzuladen, zu validieren und an das BfR zu senden. Der Probeneinsendebogen ist unter Probendaten \ Excel-Vorlage verlinkt und steht auf der gewohnten BfR-Seite zur Verfügung.

**Comment by birgitlewicki** [comment]
Text on startpage of the ADV portal is changed.

**Comment by afalenski** [comment]
Done.
