### ISSUE TITLE
Change text on the startpage of the MiBi-Portal AVV

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#559]
Exchange text in the first two paragraphs on the startpage of the MiBi-Portal AVV, leave the rest of the text as before.

**Old:**
Sie befinden sich auf dem neuen Datenaustausch-Portal der mikrobiologischen nationalen Referenzlabore des Bundesinstituts für Risikobewertung (BfR).

Hier haben Sie die Möglichkeit sich zu registrieren und nach dem Einloggen Ihre im Probeneinsendebogen eingetragenen Daten hochzuladen, zu validieren und an das BfR zu senden. Der Probeneinsendebogen ist unter Probendaten \ Excel-Vorlage verlinkt und steht auf der gewohnten BfR-Seite zur Verfügung. 

**New:**
Sie befinden sich auf dem Datenaustausch-Portal der mikrobiologischen nationalen Referenzlabore des Bundesinstituts für Risikobewertung (BfR).

Hier haben Sie die Möglichkeit sich zu registrieren und nach dem Einloggen Ihre im Probeneinsendebogen eingetragenen AVV DatA-codierten Daten hochzuladen, zu validieren und an das BfR zu senden. Der Probeneinsendebogen ist unter Probendaten \ Excel-Vorlage verlinkt und steht auf der gewohnten BfR-Seite zur Verfügung.

**Comment by birgitlewicki** [comment]
Text changed on startup page of AVV portal

**Comment by afalenski** [comment]
Done.
