### ISSUE TITLE
Exchange Einsendebogen v17 with the latest - again

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#563]
As NRL user I would like to see the the latest layout of Einsendebogen v17 and Einsendebogen-LIMS.

The latest version was sent to BL on 22.12.2023.

**Comment by birgitlewicki** [comment]
Einsendebogen v17 is exchanged.

**Comment by afalenski** [comment]
Sent LIMS-Einsendebogen and exported Einsendebogen are new.
Done.
