### ISSUE TITLE
PDF contains old footer

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#564]
Please exchange the footer in the PDF:

Outdated text: "OE-Mibi-SOP-059_FB_A01_Elektronischer Einsendebogen_V16 gültig ab 26.06.2023"
Current text in Einsendebogen Version 17: "OE-Mibi-SOP-059_FB_A01_Elektronischer Einsendebogen_V17 gültig ab 01.01.2024"

**Comment by birgitlewicki** [comment]
The footer is fixed.

**Comment by afalenski** [comment]
New footer in place.
Done.
