### ISSUE TITLE
If ZoMo, then no warning for Planprobe in NRL-AR

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#565]
As a user who is uploading a ZoMo sample I do not want to get a warning because of the AVV DatA-Code for Planprobe if it is for NRL-AR.

There is a warning that NRL-AR should not get "Planprobe". This is still valid. However, as the reason for samples is split into Kontrollprogramm and Untersuchungsgrund, it is the only possibility to notify about a "Zoonosen-Monitoring Planprobe" by giving the code "70564|53075|" (Zoonosen-Monitoring) in column "Kontrollprogramm" and the code "22562|126354|" (Planprobe) in column "Untersuchungsgrund".

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cc18627e7accb30c24db47480fec7207f6a3341/grafik.png" alt="grafik.png" />

- Please add an if-statement to the current warning (validationerror 95): Activate rule 95 only if lab = NRL-AR AND Untersuchungsgrund = "22562|126354|" AND Kontrollprogramm != (IS NOT) "70564|53075|"

There is the possibility that someone writes "Zoonosen-Monitoring" into the text column and the code for Planprobe into the column "Untersuchungsgrund", but this is not part of this ticket.

**Comment by birgitlewicki** [comment]
Validation error 95 implemented as described.

**Comment by afalenski** [comment]
- Warning appears for NRL-AR if code for "Planprobe" is given.
- Warning does not appear for other NRLs.
- Warning does not appear for NRL-AR if codes for "Planprobe" AND ZoMo are given.
Done.
