### ISSUE TITLE
If there is a user text, always write User in PDF

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#566]
As NRL user I would like to differ user entries from AVV DatA texts.

- If there is a user text, always write "User: " before the individual user text in the PDF, also if there is only this user text and no AVV DatA text. This applies to Ort and Betriebsart; in "Tiere / Matrix (Text)" and in "Kontrollprogramm / Untersuchungsgrund (Text)" this rule already seems to be active.

**Comment by birgitlewicki** [comment]
The prefix 'User' is added in the case of user text

**Comment by afalenski** [comment]
Inroductory text "User: " is always in the PDF, even if only user text is given. Great!
Done.
