### ISSUE TITLE
Cell is coloured in the Excel sheet for BfR labs

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#570]
In the Excel sheet for BfR labs sent by the MiBi-Portal ("LIMS-Excel") the wrong cell is coloured. No cell should be coloured.

**Please do not colour any cell in the LIMS Excel.**

~~In data row 3 the animal code lacks the final pipe. When it is corrected and an email sent, the cell in column "Ort der Probe-nahme (Text)" in the same row is coloured instead of the cell for the animal code.~~
~~Assumption: The Excel sheet for BfR labs has more columns than the uploaded Einsendebogen because it also contains the text translations of the code. Perhaps the cell colouring was not adapted to the new situation with additional columns.~~

**To Reproduce**
1. Upload the test sheet "Einsendebogen-v17_20231210_BetriebsartenTiereMatrices.xlsx" sent to BL on 05.01.2024
2. Correct the animal code in row 3 (sample no. 1234562) by adding a pipe
3. Login and send the file
4. Open the sent Excel sheet (or skip step 3 and just open file "- mpc570_Bug_Einsendebogen-v17_20231210_BetriebsartenTiereMatrices_NRL-AR_validated.xlsx")
Cell K44 is coloured (Ort der Probenahme (Text)) instead of cell L44 (the animal code cell).
File "mpc570_Wrong_column coloured in sheet sent to BfR_NRL-AR_validated.xlsx" shows wrongly coloured cells for all AVV code columns.
______
**Tested with**
Machine: BfR-Laptop
OS: Windows 10

Browsers:
- Firefox 115.5.0esr (64-Bit)

Files:
- Einsendebogen-v17_20231210_BetriebsartenTiereMatrices.xlsx
- mpc570_Bug_Einsendebogen-v17_20231210_BetriebsartenTiereMatrices_NRL-AR_validated.xlsx
- mpc570_Wrong column coloured in sheet sent to BfR.xlsx
- mpc570_Wrong_column coloured in sheet sent to BfR_NRL-AR_validated.xlsx

**Comment by birgitlewicki** [comment]
Cell coloring in LIMS Excel is disabled now.
Deployed on qa.

**Comment by afalenski** [comment]
There is a bug in epilab-dev: No Einsendebögen are loaded. Please fix.

**Comment by afalenski** [comment]
Therer is no colouring of cells in the LIMS-Excel anymore.
Done.
