### ISSUE TITLE
Nolar-dev/login in Popup

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#579]
As a user who has logged into the AVV MiBi-Portal and who uploads an Einsendebogen V16 or earlier, I want to be re-directed directly to the MiBi-Portal ADV login page so that I do not forget to login again.

- exchange https://nolar-dev.bfr.berlin against https://nolar-dev.bfr.berlin/users/login in the popup.

**Comment by birgitlewicki** [comment]
deployed on qa

**Comment by afalenski** [comment]
- Link is changed and works.
- Data upload and sending works for ADV and AVV, PDF and XLSX are fine.
Thank you for the quick implementation!
Done.

**Comment by dptolle** [comment]
@afalenski Why was this moved back to 'In Progress'?
