### ISSUE TITLE
Redirect ADV user endpoints to AVV host

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#580]

**Comment by dptolle** [comment]
@afalenski As Birgit rightly pointed out, this ticket does not address the User story outlined in the ticket description.  It is, however a necessary first step required to do so.

**Comment by dptolle** [comment]
First test this locally (developer).  Then deploy ADV system to QA and test if you can log in with mibi AVV Prod user.

**Comment by dptolle** [comment]
I reverted the commit - ran into some SOP issues which I can't fix due to not being able to change the configuration of the nginx.  I will try and find a server-side solution
