### ISSUE TITLE
Exchange list of additional pathogens

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#589]
As a user from a BfR lab I would like the MiBi-Portal to recognise our new selection of additional pathogens in the MiBi-Portal.

Please exchange the old "Erreger-Zusatzliste" against the one sent to BL on 05.02.2024.

**Comment by birgitlewicki** [comment]
implemented on qa:

- updated locally avv324.json with new Erreger-Zusatzliste with master-data script
- copied manually avv324.json from local system to qa system into the data folder of mibi-portal
- restarted server

**Comment by afalenski** [comment]
Great! Additional pathogens are recognised and the correct BfR lab is shown.
Done.
