### ISSUE TITLE
Make Excel output pretty

### ISSUE THREAD

**Issue by dptolle** [SiLeBAT/mibi-portal-client#59]
As a portal user I would like to have the downloaded excel file in the same format as the uploaded excel file.

**Comment by draaw** [comment]
The original Excel file is located here: http://www.bfr.bund.de/cm/343/Einsendebogen_v14.xlsx

xlsx-populate (https://github.com/dtjohnson/xlsx-populate) seems to be a solution, e.g.:

-------------Frontend Code from https://gitcdn.xyz/cdn/dtjohnson/xlsx-populate/32921c0b357828cf4c9065c60aa5ab9ad5aefd62/examples/browser/index.html -------------------
			    function manipulateXlsx(file) {
			    	window.IQc = { entity: 'x', ENTITIES: { x: 'x' } }
			        return generate(file)
			            .then(function (blob) {
			                if (window.navigator && window.navigator.msSaveOrOpenBlob) {
			                    window.navigator.msSaveOrOpenBlob(blob, "out1.xlsx");
			                } else {
			                    var url = window.URL.createObjectURL(blob);
			                    var a = document.createElement("a");
			                    document.body.appendChild(a);
			                    a.href = url;
			                    a.download = "out2.xlsx";
			                    a.click();
			                    window.URL.revokeObjectURL(url);
			                    document.body.removeChild(a);
			                }
			            })
			            .catch(function (err) {
			                alert(err.message || err);
			                throw err;
			            });
			    }

			 function getWorkbook(file) {
		            //var file = fileInput.files[0];
		            if (!file) return Promise.reject("You must select a file.");
		            return XlsxPopulate.fromDataAsync(file);
			    }			 
			    function generate(file) {
			        return getWorkbook(file)
			            .then(function (workbook) {
			                workbook.sheet(0).cell("A1").value("This was created in the browser!").style("fontColor", "ff0000");
			                return workbook.outputAsync();
			            });
			    }
-------------------------------------

**Comment by birgitlewicki** [comment]
implemented and deployed
