### ISSUE TITLE
Colour pathogen cell if the portal has translated a code

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#600]
As a user from the BfR labs I would like to recognise whether a pathogen text was written by the uploader of the Einsendebogen or whether the portal has translated a code into text.

- Colour a pathogen cell (column "Erreger (Code oder Text aus AVV DatA-Kat-Nr. 324)") if autocorrection from code to text happened.

**Comment by birgitlewicki** [comment]
Hotfix deployed on qa.
Please test.

**Comment by birgitlewicki** [comment]
Hotfix deployed on production.
