### ISSUE TITLE
Update AVV catalogues

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#601]
As a user I would like the MiBi-Portal to check my AVV DatA codes against the latest catalogues.

- Exchange the catalogues 313, 316, 319, 322, 324, 326, 328, 339 (see email from AF). Only 303 stays the same.
- If there are any problems: Skada contains now also introductory texts which might help (click into the white space of a catalogue row as if to download the catalogue)

**Comment by birgitlewicki** [comment]
All these 8 AVV catalogs are installed on the productive AVV mibi portal and can be used for checking AVV DatA codes.

**Comment by birgitlewicki** [comment]
All newest AVV catalogs are installed on the prod system.
Done.
