### ISSUE TITLE
MiBi-Portal accepts invalid AVV319 and AVV339 codes

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#605]
The MiBi-Portal accepted code 182335|185012|183670-1101:6748 as valid. However, although all parts of the code are existing codes, the whole code is invalid due to SKaDa. 182335|185012| is a hierarchy entry and not a 'basiseintrag'. Thus, no facettes may be added. The hierarchy code 182335|185012| itself is valid, if no facette is added.

- Applies to matrix catalogue AVV319 and to animal catalogue AVV339
- A matrix or animal code with facettes is only valid, if an "Eintrag" in the AVV XML file contains the attribute 'basiseintrag="true"'.
- For 'basiseintrag="false"', only codes can be valid which contain digits up to the second pipe (nnnnn|nnnn|); they may not have facettes. If facettes are added, the client should show error 33 / error 99 and sending the data to BfR should not be possible.
- Adaptations to the parsing of the XML catalogue are necessary.

Dev notes:
- First try: When creating the catalogue JSON file, only copy facette catalogue IDs if the entry is a 'Basiseintrag'.
- Second idea: Note in the JSON catalogue whether an entry is a 'Basiseintrag' and add rule to the MiBi-Portal validations: If 'basiseintrag="false"', an uploaded matrix/animal code may not exceed the second pipe; if so, the code is invalid.

**Comment by birgitlewicki** [comment]
Fixed and deployed on qa.
