### ISSUE TITLE
Automatic error correction for final pipe after facettes

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#606]
As a LIMS user I do not want to import a matrix or animal code which is ivalid only because of a final pipe.

- If an animal code (AVV339), a Betriebsart code (AVV303) or a matrix code (AVV319) consists of a Basiscode AND facettes, check whether there is a pipe at the end. If yes, delete the pipe.
- Add a new error code:
Error Code: 109
Level: 4
Message: "Abgesehen von dem finalen senkrechten Strich ist der Code korrekt. Der Strich wurde entfernt."
To be checked in 3 columns: Betriebsart (Code aus AVV DatA-Kat-Nr. 303), Tiere (Code aus AVV DatA-Kat-Nr. 339), Matrix (Code aus AVV DatA-Kat-Nr. 319)
- As for all auto-corrections, colour the cell in blue.
- Do NOT delete the final pipe of a Basiscode if there is no facette. The uploaded code would become invalid.
- Hotfix

**Comment by birgitlewicki** [comment]
Autocorrection implemented for the 3 columns.
Error code of the new validation error message is 109.

**Comment by birgitlewicki** [comment]
Fixed and deployed on qa.
Please test.

**Comment by afalenski** [comment]
- Uploading an Einsendebogen containing a valid AVV339 code produces not an MiBi-Portal error anymore.
- If there are other characters after the final digit of the code, the code is invalid and the portal now shows an error.

Bug:
- When you upload an Einsendebogen with the code "9171|187178|185142-61004|||", the portal deletes the final pipe and highlights the cell in blue, but the code still contains two final pipes. When you login and click on the "Senden" button, the toaster message "Es wurden Felder autokorregiert. Bitte prüfen und nochmals senden." appears and one additional pipe is deleted. But this small change will hardly be noticed by the user, who will certainly become confused. You could click on "Nochmals senden", but then the message appears again. Only if you then click an additional time on "Nochmals senden", the wizard appears and the code finally has no pipe at the end anymore.

Three different ideas:
1) Could the portal check whether the code is valid after deleting the final pipe, please? I would have expected the portal to show an error for the code shown above. 
2) Deleting all final pipes and checking for code validity could also be a helpful solution for the user. 
3) We could also say that a final pipe is just as invalid as a final question mark and that it is not to be corrected automatically. The code shown above should produce an error, regardless of the number of final pipes (so also with just one final pipe). Then this ticket should be renamed 'Show error for invalid final pipe'.
- The word "autokorregiert" does not exist and "korrigiert" is written with two 'i'. Please exchange the wording:
Old:  "Es wurden Felder autokorregiert. Bitte prüfen und nochmals senden."
New: "Es wurden Felder automatisch korrigiert. Bitte prüfen und nochmals senden."

Please fix.

**Comment by afalenski** [comment]
Decision not to autocorret final pipes. If a final pipe or any other character is added to a valid code, the code is invalid (red error message).

**Comment by birgitlewicki** [comment]
The correct validation of wrong codes is implemented.
The autocorrection of the final pipe after facettes is removed, it is now part of the normal validation.
Deployed on qa.

**Comment by afalenski** [comment]
- If there are final pipes (where not correct) and other special characters, the MiBi-Portal shows an AVV error. Good!
- All test pre-defined sheets are validated correctly.
- **The error code 109 is still in the dashboard. Please delete this error code and the message everywhere.** Number 109 can then be used for a future error message.
- A faulty code accepted: 14189|558| (can be tested again in mpc610).
