### ISSUE TITLE
Date check: Sampling and isolation on same day should be possible

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#61]
Please upload the test sheet 
[Einsendebogen-v14_Legende für Farbcodes_Ecoli1_ZSP2018.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/1850713/Einsendebogen-v14_Legende.fur.Farbcodes_Ecoli1_ZSP2018.xlsx), change in line 3 "31.06.2017" to "30.06.2017" and validate. Now the sampling is on the same day as the isolation. The Mibi-Portal shows an error and asks whether the sampling was after the isolation (which is wrong, obviously). Sampling and isolation can be on the same day and should be no error.

**Comment by dptolle** [comment]
On develop & needs to be deployed
