### ISSUE TITLE
Implement new AVV DatA catalogues

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#615]
As a user I would like the MiBi-Portal to check my codes against the latest AVV DatA catalogues.

- Exchange old catalogues against the new ones.
Catalogue files: See email to BL on 28.06.2024

**Comment by birgitlewicki** [comment]
All the newest catalogs are loaded on the prod system.

**Comment by afalenski** [comment]
Seven of the nine catalogues contained new and testable entries. All were found by the MiBi-Portal.
Done.
______
**Tested with**
Machine: BfR-Laptop

OS: Windows 10

Datasets: 
mpc615_AVV-Kataloge_20240819.xlsx

Browsers:
- Firefox 115.13.0esr (64-Bit)
