### ISSUE TITLE
Wrong Mibi-Portal error message: Matrix code not unambiguous

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#62]
Please upload the test sheet (see #61) and hover with the mouse over the red coloured cell in line 7: A gigantic speech bubble opens containing an error message (last part repeated many times) which is not correct. In line 7 there is a "Oberbegriff" (code 15) and thus the matrix code (101030) is unambiguous. This error should not be displayed. Only without the "Oberbegriff" the displayed error would be correct, but in this case there should be only the first 3 sentences. The last one should not be repeated so many times.

**Comment by dptolle** [comment]
Fixed & ready for deploy

**Comment by afalenski** [comment]
Excellent! All fine.
