### ISSUE TITLE
Display error if identical sample numbers and agents are used in 2 lines

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#63]
Please upload the test sheet (see #61), copy both "Ihre Probenummer" and "Probenummer nach AVVData" from line 1 to line 2 and validate. Although in both lines the two sample numbers as well as the agent are identical, no error is shown for identical sample numbers. The problem here is probably that the agent in line 2 is given in both "Erreger" columns while in line 1 it is only given in the first "Erreger" column. However, in line 2, column 3 the agent name is identical to the one in column 4 and thus the error for identical sample numbers should be displayed.

**Comment by draaw** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #46](https://github.com/SiLeBAT/mibi-portal-server/issues/46) via [**ZenHub**](https://www.zenhub.com/)
