### ISSUE TITLE
Include checks for ADV12

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#64]
Please upload the test sheet (see #61) and enter in any cell in column 13 "062" and validate. This ADV12 code does not exist and it should be shown as error. As no error is shown and because in lines 3 and 4 both "052" (correct ADV code) and "52" (not a correct code) are accepted it seems as if column 13 was not checked against the ADV12 catalogue. Please include this check and display error messages (see, for example, Workflow "MiBi-Portal_v14_07", Java Snippet node 1271).

**Comment by dptolle** [comment]
Issue moved to [SiLeBAT/mibi-portal-server #26](https://github.com/SiLeBAT/mibi-portal-server/issues/26) via [**ZenHub**](https://www.zenhub.com/)
