### ISSUE TITLE
Make current UI pretty

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#65]
As a mibi portal user I'd like to enjoy the following UI improvements:

- no/minimal space in content area of the table, maybe with border
- remove shadow of navbar
- remove shadow from navbar buttons
- footer smaller

**navbar:**
- background blue: rgb(3, 78, 168)
- font white
- hover: bold + larger font
- login info: dropdown with login name, logout option

**Comment by draaw** [comment]
- Beneath "Probendaten"
  - please rename "Speichern" with "Download"
  - "Validieren" should be more visible - it is "too hidden"
- Resizing of the whole Window results in an overlap of the table with the footer
- Mouse Over the Links in the header results in irritating "flips", this counts for the submenu as well

**Comment by birgitlewicki** [comment]
- The menu item 'Validieren' was moved back to the main navigation bar to have it more prominent.

- Resizing the window does not resize the table: this seems to be a feature of handsontable, the workaround is to load the data into the table again after resizing the window.

**Comment by draaw** [comment]
- still not solved: Resizing of the whole Window results in an overlap of the table with the footer. What about catching the window resize event?
- not touched: Mouse Over the Links in the header results in irritating "flips", this counts for the submenu as well
- not touched (from the first comment): no/minimal space in content area of the table, maybe with border

**Comment by birgitlewicki** [comment]
- table resizes now when window is resized

- hovering on header items now changes font color, hovering dropdown menu items just change background color

- 'Hochladen' is changed to 'Upload'

**Comment by draaw** [comment]
After clicking "Download und Senden" (and the upcoming of the '"toaster") the table is again too big - needs a resize event

**Comment by birgitlewicki** [comment]
When loading sample data of a 'big' excel sheet having e.g. 50 rows of data the following ui effects occurs in the deployed version:

- Doubleclicking a field in a higher row number e.g. row 30 results in 'disappearing' of the whole table, it appears again normally when it is clicked somewhere on the page or leaving the table field from the editable mode in another way e.g. using the tab.

- When a field is selected by clicking on it and then scrolling the table by using the scrollbar the selected field keeps staying on the page.

These effects are not observable on the local development version.

**Comment by birgitlewicki** [comment]
- fixed: resizing table with upcoming toaster

- fixed: 'strange' doubleclicking ui effects described in previous comment
