### ISSUE TITLE
Change menu item 'Download und Senden' to 'Senden'

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#67]
As a mibi user I want to send my excel sheet with the validated data to the corresponding recipient and simultanously I want to get a copy of it per mail to my login address.

**Comment by draaw** [comment]
Sending is too prompt. It would be better to introduce an intermediate step - a confirmation step, like "Wollen Sie Ihre Probendaten jetzt an das BfR senden?"
