### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#69]
Minor bug: Please upload the test sheet 
[Einsendebogen-v14_Legende für Farbcodes_Ecoli1_ZSP2018.xlsx](https://github.com/SiLeBAT/mibi-portal-client/files/1850713/Einsendebogen-v14_Legende.fur.Farbcodes_Ecoli1_ZSP2018.xlsx) and have a look at the error messages in the date columns in row 5. There are three error messages of which at least one is wrong ("Dieses Datum gibt es nicht") and one is duplicate. The most precise error message will help users the most and this is why - in this case - only the message "Datum fehlt (Pflicht bei ZoMo)" should be displayed. At least the wrong one should not appear anymore.

**Comment by draaw** [comment]
The text for error number 19 should be changed in order to be more precise about the problem from "Datum fehlt" into "Entweder Probenahme- oder Isolationsdatum muss angegeben werden"

**Comment by afalenski** [comment]
Thinking again about the error message I think the new one is also misleading because in case of reason 81 both dates need to be given. Thus it would be best if the message would be: "Bei ZoMo müssen sowohl Probenahme- als auch Isolationsdatum angegeben werden." And if one date is given and the sheet is validated again, then the message "Datum fehlt (Pflicht bei ZoMo)" should appear. The message "Entweder Probenahme- oder Isolationsdatum muss angegeben werden" should only appear, if no date is given and the reason is NOT "81" or "Zoonosen-Monitoring - Planprobe".

**Comment by draaw** [comment]
That's exactly covered by Ticket mps#45

**Comment by afalenski** [comment]
I copied my comment to mps#45. Now this ticket is duplicate.
