### ISSUE TITLE
Print hint needs to be added

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#74]
As a portal user I need a reminder that I do also have to print the Excel sheet to be able to add the printout to the physical box.
The reminder should be part of the confirmation box (or after) during the sending process and additionally part of the mail that goes to the sender
Text suggestion: "Bitte vergessen Sie nicht die Exceltabelle in Ihrem Mailanhang auszudrucken und Ihren Isolaten beizulegen"

**Comment by birgitlewicki** [comment]
Implemented.
Ready for deployment.

**Comment by draaw** [comment]
The print hint is still not part of the confirmation box, see ticket above

**Comment by birgitlewicki** [comment]
Fixed.

**Comment by afalenski** [comment]
I could not see any print reminder. A green ribbon saying "Auftrag wurde an das BfR gesendet." appeared and I received an email, that was all.

**Comment by afalenski** [comment]
Testing with the second Epilab-Link I found the link. Done.
