### ISSUE TITLE
Add menue point for template

### ISSUE THREAD

**Issue by birgitlewicki** [SiLeBAT/mibi-portal-client#75]
At menu point 'Probendaten' add link for excel template
'Excel-Vorlage'

**Comment by afalenski** [comment]
Link to webpage where the 'Excel-Vorlage' can be found: http://www.bfr.bund.de/de/einsendeformular_fuer_isolate_und_proben-9257.html

**Comment by afalenski** [comment]
I cannot see the link to the Excel-Vorlage. I searched for it in the menu "Probendaten" and in the footer.

**Comment by afalenski** [comment]
I tested with the second epilab-link and everything is fine. Done.
