### ISSUE TITLE
Self-define institute name

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#80]
As a portal user I want to define the name of my institute on my own - in case it is not in the predefined list

DevNote: see for an example here: http://jsfiddle.net/pjagana/49rk6ph7/

**Comment by birgitlewicki** [comment]
Implemented and pushed.

TODO:
import script for new institute

**Comment by birgitlewicki** [comment]
import script for unknown institute added

=> deployed and ready for testing

**Comment by draaw** [comment]
import script looks pretty good. Can you please provide the syntax for calling the script with the json file?
