### ISSUE TITLE
Changed entries in table need to be validated before sending them

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#82]
As a portal user I would like to be warned if I am going to send or download my online-changed data without making use of the "Validieren" function before.
Suggestion: add a warning into the "toaster" saying "Sie haben Änderungen gemacht, die noch nicht validiert wurden. Bitte validieren Sie Ihre Daten vor dem Senden."

**Comment by draaw** [comment]
Alex suggested to automatically validate and send in case the validation  returns no errors, hints or warnings.

**Comment by draaw** [comment]
New message would be: "Sie haben nach dem letzten Validierungsvorgang Änderungen gemacht, die zu neuen Ergebnissen führen. Wenn Sie dennoch senden wollen, dann klicken Sie bitte nochmals Senden."

**Comment by draaw** [comment]
nearly perfect, except:
imagine you have two warnings in your data. Then you correct one warning. Then you press "Senden". But the data will not be sent although you have improved the data (there is only ONE warning left)

**Comment by birgitlewicki** [comment]
Tracking of new warnings is handled now via the cell coordinates of the cells with warnings. This works as long as we don't add or delete any cells in the table which we don't do currently.
