### ISSUE TITLE
Mibi-Portal start page: Scroll bar needed

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-client#87]
As a Mibi-Portal user working with a horizontally 'split' screen (upper half: browser, lower half: Excel or LIMS) I would like to be able to read the complete welcome text on the Mibi-Portal main page (https://mibi-portal.bfr.bund.de/). The scroll bar should appear exclusively when text on the main page cannot be seen completely.

**Comment by draaw** [comment]
done
