### ISSUE TITLE
Need for a FAQ

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-client#96]
As a portal user I would like to look into a FAQ.

Note: Look into already asked questions - via email

**Comment by afalenski** [comment]
Please see FAQ suggestions in email (28.08.2018 17:41) and give feedback or send to DT.

**Comment by dptolle** [comment]
See email: 10.09.2018 - 14:06

**Comment by draaw** [comment]
Please use as URL for the Link for "MiBi-Portal-Weblinks" the URL in the config file

**Comment by afalenski** [comment]
Looks great!
